//automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace OttieniToken.MOToken.Model
{
	/// <summary>
	/// The table contains data present in the TAX Summary of the Total tab. The TAX amount is not calculated line by line but it is grouped by percentage. After having calculated taxable amounts subject to the different percentages, the tax amount is determined and totals are calculated. It is a slave buffered of the table MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdTaxSummaryObj  : BaseEntity
	{
		//add your code here
	}	

	public partial class MA_SaleOrdTaxSummary : MA_SaleOrdTaxSummaryObj
	{
		//add your code here
	}
}