//automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace OttieniToken.MOToken.Model
{
	/// <summary>
	/// This table contains the details of the customer order and it is a slave one to many of the MA_SaleOrd table.
	/// </summary>
	public partial class MA_SaleOrdDetailsObj  : BaseEntity
	{
		//add your code here
	}	

	public partial class MA_SaleOrdDetails : MA_SaleOrdDetailsObj
	{
		//add your code here
	}
}