//automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace OttieniToken.MOToken.Model
{
	/// <summary>
	/// The table contains Sale order payment schedules. It is used only when a customized payment is set (MA_SaleOrd NonStandardPayment). It is a slave buffered of the table MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdPymtSchedObj  : BaseEntity
	{
		//add your code here
	}	

	public partial class MA_SaleOrdPymtSched : MA_SaleOrdPymtSchedObj
	{
		//add your code here
	}
}