//automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace OttieniToken.MOToken.Model
{
	/// <summary>
	/// The table contains information present in the Total tab and in the Charges tab of Sale Orders. Some fields are automatically calculated as totals of document data. These values cannot be modified by the user.
///Other data must be manually entered by the user when filling in the document and can be modified.
///It is a buffered table of the MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdSummaryObj  : BaseEntity
	{
		//add your code here
	}	

	public partial class MA_SaleOrdSummary : MA_SaleOrdSummaryObj
	{
		//add your code here
	}
}