// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace Courses.Courses.Model
{
	
	/// <summary>
	/// 
///        This table contains the activity codes
///      
	/// </summary>
	public partial class MA_ActivityCodesObj  : MasterEntity
	{
		public MA_ActivityCodesObj()
		{
		}

		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: ""
		/// </summary>
		[TbPrimaryKey(0)]

		public string ActivityCode { get =>  f_ActivityCode.TypedDBValue;  set { f_ActivityCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ActivityCode { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Description { get =>  f_Description.TypedDBValue;  set { f_Description.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Description { get ; private set; } = new DataStr();




	}	

	[Table("MA_ActivityCodes")]
    [TbEntityTypeConfiguration(typeof(MA_ActivityCodesConfiguration))]
	public partial class MA_ActivityCodes : MA_ActivityCodesObj
	{
		public MA_ActivityCodes()
			:base()
		{
		}
	}

	public sealed class MA_ActivityCodesConfiguration : MA_ActivityCodesConfiguration<MA_ActivityCodes>
	{
		public MA_ActivityCodesConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_ActivityCodes> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_ActivityCodesConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_ActivityCodesObj
    {
        public MA_ActivityCodesConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => e.ActivityCode).HasName("PK_ActivityCodes").IsClustered(false);
		#else
			entity.HasKey(e => e.ActivityCode).HasName("PK_ActivityCodes").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.ActivityCode).HasMaxLength(10).IsRequired().HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Description).HasMaxLength(256).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbGuid).IsRequired().HasDefaultValueSql("NEWID()");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.ActivityCode).HasMaxLength(10).IsRequired().HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Description).HasMaxLength(256).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbGuid).IsRequired().HasDefaultValueSql("uuid_generate_v1()");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_ActivityCodes
	/// </summary>
	public class ActivityCodesAggregate<TContext> : BaseTbAggregate<TContext, MA_ActivityCodes>
                                                                            where TContext : TbDbContext
    {
        public ActivityCodesAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_ActivityCodes> Query(string activityCode)
			=> EntityDbSet.Where(x => x.ActivityCode == activityCode);

		#region SyncMethods 
		/// <summary>
		/// Return ActivityCodes based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="activityCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetActivityCodes<TResult>(string activityCode,
		                                       Expression<Func<MA_ActivityCodes, TResult>> selector, TResult @default = default)		
			=> Result(Query(activityCode).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of ActivityCodes based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="activityCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetActivityCodesTbResult<TResult>(string activityCode,
		                                                          Expression<Func<MA_ActivityCodes, TResult>> selector, TResult @default = default)
			=> TbResult(Query(activityCode).Select(selector), @default);

		/// <summary>
		/// Return ActivityCodes based on primary key parameters default of MA_ActivityCodes if not found
		/// </summary>
        /// <remarks>Prefered to use GetActivityCodes with selector parameter</remarks>
		
		/// <param name="activityCode"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_ActivityCodes or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetActivityCodes with selector parameter")]
        public MA_ActivityCodes GetActivityCodes(string activityCode,
												   MA_ActivityCodes @default = default)
			=> Result(Query(activityCode), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return ActivityCodes based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="activityCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetActivityCodesAsync<TResult>(string activityCode,
		                                       Expression<Func<MA_ActivityCodes, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(activityCode).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of ActivityCodes based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="activityCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetActivityCodesTbResultAsync<TResult>(string activityCode,
		                                                          Expression<Func<MA_ActivityCodes, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(activityCode).Select(selector), @default);

		/// <summary>
		/// Return ActivityCodes based on primary key parameters default of MA_ActivityCodes if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetActivityCodes with selector parameter</remarks>
		
		/// <param name="activityCode"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_ActivityCodes or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetActivityCodes with selector parameter")]
        public Task<MA_ActivityCodes> GetActivityCodesAsync(string activityCode,
												   MA_ActivityCodes @default = default)
			=> ResultAsync(Query(activityCode), @default);

		#endregion 
		
    }

}