// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace Courses.Courses.Model
{
	
	/// <summary>
	/// 
	/// </summary>
	public partial class MA_BillOfMaterialsToolsObj  : BaseEntity
	{
		public MA_BillOfMaterialsToolsObj()
		{
		}

		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: ""
		/// </summary>
		[TbPrimaryKey(0)]

		public string BOM { get =>  f_BOM.TypedDBValue;  set { f_BOM.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_BOM { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(1)]

		public Int32 Line { get =>  f_Line.TypedDBValue;  set { f_Line.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_Line { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? IsFamily { get =>  f_IsFamily.TypedDBValue;  set { f_IsFamily.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_IsFamily { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Tool { get =>  f_Tool.TypedDBValue;  set { f_Tool.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Tool { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? RtgStep { get =>  f_RtgStep.TypedDBValue;  set { f_RtgStep.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_RtgStep { get ; private set; } = new DataInt();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Alternate { get =>  f_Alternate.TypedDBValue;  set { f_Alternate.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Alternate { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? AltRtgStep { get =>  f_AltRtgStep.TypedDBValue;  set { f_AltRtgStep.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_AltRtgStep { get ; private set; } = new DataInt();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 28508160
		/// </summary>

		public int? ProcessingType { get =>  f_ProcessingType.TypedDBValue;  set { f_ProcessingType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_ProcessingType { get ; private set; } = new DataEnum(28508160);



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Fixed { get =>  f_Fixed.TypedDBValue;  set { f_Fixed.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Fixed { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? UsageQuantity { get =>  f_UsageQuantity.TypedDBValue;  set { f_UsageQuantity.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_UsageQuantity { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? UsageTime { get =>  f_UsageTime.TypedDBValue;  set { f_UsageTime.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_UsageTime { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? ExclusiveUse { get =>  f_ExclusiveUse.TypedDBValue;  set { f_ExclusiveUse.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_ExclusiveUse { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 2032009216
		/// </summary>

		public int? Usage { get =>  f_Usage.TypedDBValue;  set { f_Usage.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_Usage { get ; private set; } = new DataEnum(2032009216);




	}	

	[Table("MA_BillOfMaterialsTools")]
    [TbEntityTypeConfiguration(typeof(MA_BillOfMaterialsToolsConfiguration))]
	public partial class MA_BillOfMaterialsTools : MA_BillOfMaterialsToolsObj
	{
		public MA_BillOfMaterialsTools()
			:base()
		{
		}
	}

	public sealed class MA_BillOfMaterialsToolsConfiguration : MA_BillOfMaterialsToolsConfiguration<MA_BillOfMaterialsTools>
	{
		public MA_BillOfMaterialsToolsConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_BillOfMaterialsTools> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_BillOfMaterialsToolsConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_BillOfMaterialsToolsObj
    {
        public MA_BillOfMaterialsToolsConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => new { e.BOM,e.Line }).HasName("PK_BillOfMaterialsTools").IsClustered(false);
		#else
			entity.HasKey(e => new { e.BOM,e.Line }).HasName("PK_BillOfMaterialsTools").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.BOM).HasMaxLength(21).IsRequired().HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Line).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.IsFamily).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Tool).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.RtgStep).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Alternate).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.AltRtgStep).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ProcessingType).HasDefaultValueSql("(28508160)")  ;
					entity.Property(e => e.Fixed).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.UsageQuantity).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UsageTime).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ExclusiveUse).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Usage).HasDefaultValueSql("(2032009216)")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.BOM).HasMaxLength(21).IsRequired().HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Line).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.IsFamily).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Tool).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.RtgStep).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Alternate).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.AltRtgStep).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ProcessingType).HasDefaultValueSql("(28508160)")  ;
					entity.Property(e => e.Fixed).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.UsageQuantity).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UsageTime).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ExclusiveUse).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Usage).HasDefaultValueSql("(2032009216)")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_BillOfMaterialsTools
	/// </summary>
	public class BillOfMaterialsToolsAggregate<TContext> : BaseTbAggregate<TContext, MA_BillOfMaterialsTools>
                                                                            where TContext : TbDbContext
    {
        public BillOfMaterialsToolsAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_BillOfMaterialsTools> Query(string bOM,Int32 line)
			=> EntityDbSet.Where(x => x.BOM == bOM && x.Line == line);

		#region SyncMethods 
		/// <summary>
		/// Return BillOfMaterialsTools based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="bOM"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetBillOfMaterialsTools<TResult>(string bOM,Int32 line,
		                                       Expression<Func<MA_BillOfMaterialsTools, TResult>> selector, TResult @default = default)		
			=> Result(Query(bOM,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of BillOfMaterialsTools based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="bOM"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetBillOfMaterialsToolsTbResult<TResult>(string bOM,Int32 line,
		                                                          Expression<Func<MA_BillOfMaterialsTools, TResult>> selector, TResult @default = default)
			=> TbResult(Query(bOM,line).Select(selector), @default);

		/// <summary>
		/// Return BillOfMaterialsTools based on primary key parameters default of MA_BillOfMaterialsTools if not found
		/// </summary>
        /// <remarks>Prefered to use GetBillOfMaterialsTools with selector parameter</remarks>
		
		/// <param name="bOM"></param>
		
		/// <param name="line"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_BillOfMaterialsTools or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetBillOfMaterialsTools with selector parameter")]
        public MA_BillOfMaterialsTools GetBillOfMaterialsTools(string bOM,Int32 line,
												   MA_BillOfMaterialsTools @default = default)
			=> Result(Query(bOM,line), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return BillOfMaterialsTools based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="bOM"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetBillOfMaterialsToolsAsync<TResult>(string bOM,Int32 line,
		                                       Expression<Func<MA_BillOfMaterialsTools, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(bOM,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of BillOfMaterialsTools based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="bOM"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetBillOfMaterialsToolsTbResultAsync<TResult>(string bOM,Int32 line,
		                                                          Expression<Func<MA_BillOfMaterialsTools, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(bOM,line).Select(selector), @default);

		/// <summary>
		/// Return BillOfMaterialsTools based on primary key parameters default of MA_BillOfMaterialsTools if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetBillOfMaterialsTools with selector parameter</remarks>
		
		/// <param name="bOM"></param>
		
		/// <param name="line"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_BillOfMaterialsTools or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetBillOfMaterialsTools with selector parameter")]
        public Task<MA_BillOfMaterialsTools> GetBillOfMaterialsToolsAsync(string bOM,Int32 line,
												   MA_BillOfMaterialsTools @default = default)
			=> ResultAsync(Query(bOM,line), @default);

		#endregion 
		
    }

}