	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace Courses.Courses.Model
{
	
	/// <summary>
	/// tabella principale corso
	/// </summary>
	public partial class MMS_CoursesObj  : MasterEntity
	{
		public MMS_CoursesObj()
		{
		}

		/// <summary>
		/// codice corso
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 CourseID { get =>  f_CourseID.TypedDBValue;  set { f_CourseID.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_CourseID { get ; private set; } = new DataLng();



		/// <summary>
		/// descrizione corso
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? CourseDescription { get =>  f_CourseDescription.TypedDBValue;  set { f_CourseDescription.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_CourseDescription { get ; private set; } = new DataStr();



		/// <summary>
		/// data inizio corso
		/// 	
		/// DefaultValue: new System.DateTime(1799, 12, 31, 0, 0, 0)
		/// </summary>

		public DateTime? CourseDate { get =>  f_CourseDate.TypedDBValue;  set { f_CourseDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDate f_CourseDate { get ; private set; } = new DataDate();



		/// <summary>
		/// livello corso
		/// 	
		/// DefaultValue: 524353536
		/// </summary>

		public int? CourseLevel { get =>  f_CourseLevel.TypedDBValue;  set { f_CourseLevel.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_CourseLevel { get ; private set; } = new DataEnum(524353536);




	}	

	[Table("MMS_Courses")]
    [TbEntityTypeConfiguration(typeof(MMS_CoursesConfiguration))]
	public partial class MMS_Courses : MMS_CoursesObj
	{
		public MMS_Courses()
			:base()
		{
		}
	}

	public sealed class MMS_CoursesConfiguration : MMS_CoursesConfiguration<MMS_Courses>
	{
		public MMS_CoursesConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MMS_Courses> entity)
		{
			base.Configure(entity);
		}
	}

	public class MMS_CoursesConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MMS_CoursesObj
    {
        public MMS_CoursesConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => e.CourseID).HasName("PK_MMS_Courses").IsClustered(false);
		#else
			entity.HasKey(e => e.CourseID).HasName("PK_MMS_Courses").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.CourseID).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.CourseDescription).HasMaxLength(64).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CourseDate).HasColumnType("datetime").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.CourseLevel).HasDefaultValueSql("(524353536)")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbGuid).IsRequired().HasDefaultValueSql("NEWID()");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.CourseID).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.CourseDescription).HasMaxLength(64).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CourseDate).HasColumnType("timestamp without time zone").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.CourseLevel).HasDefaultValueSql("(524353536)")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbGuid).IsRequired().HasDefaultValueSql("uuid_generate_v1()");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MMS_Courses
	/// </summary>
	public class MMS_CoursesAggregate<TContext> : BaseTbAggregate<TContext, MMS_Courses>
                                                                            where TContext : TbDbContext
    {
        public MMS_CoursesAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MMS_Courses> Query(Int32 courseID)
			=> EntityDbSet.Where(x => x.CourseID == courseID);

		#region SyncMethods 
		/// <summary>
		/// Return MMS_Courses based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetMMS_Courses<TResult>(Int32 courseID,
		                                       Expression<Func<MMS_Courses, TResult>> selector, TResult @default = default)		
			=> Result(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of MMS_Courses based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetMMS_CoursesTbResult<TResult>(Int32 courseID,
		                                                          Expression<Func<MMS_Courses, TResult>> selector, TResult @default = default)
			=> TbResult(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return MMS_Courses based on primary key parameters default of MMS_Courses if not found
		/// </summary>
        /// <remarks>Prefered to use GetMMS_Courses with selector parameter</remarks>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MMS_Courses or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetMMS_Courses with selector parameter")]
        public MMS_Courses GetMMS_Courses(Int32 courseID,
												   MMS_Courses @default = default)
			=> Result(Query(courseID), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return MMS_Courses based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetMMS_CoursesAsync<TResult>(Int32 courseID,
		                                       Expression<Func<MMS_Courses, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of MMS_Courses based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetMMS_CoursesTbResultAsync<TResult>(Int32 courseID,
		                                                          Expression<Func<MMS_Courses, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return MMS_Courses based on primary key parameters default of MMS_Courses if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetMMS_Courses with selector parameter</remarks>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MMS_Courses or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetMMS_Courses with selector parameter")]
        public Task<MMS_Courses> GetMMS_CoursesAsync(Int32 courseID,
												   MMS_Courses @default = default)
			=> ResultAsync(Query(courseID), @default);

		#endregion 
		
    }

}