// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace Courses.Courses.Model
{
	/// <summary>
	/// MMS_Courses_Virtual
	/// </summary>
	public partial class MMS_Courses_Virtual : BaseEntity
	{
		public MMS_Courses_Virtual()
		{
		}

		
		[NotMapped]
		public Int32? CourseId { get =>  f_CourseId.TypedDBValue;  set { f_CourseId.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataLng f_CourseId { get ; private set; } = new DataLng();

		
		[NotMapped]
		public string? Description { get =>  f_Description.TypedDBValue;  set { f_Description.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_Description { get ; private set; } = new DataStr();

		
		[NotMapped]
		public int? CourseLevel { get =>  f_CourseLevel.TypedDBValue;  set { f_CourseLevel.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataEnum f_CourseLevel { get ; private set; } = new DataEnum(531496960);

		
		[NotMapped]
		public string? Teacher { get =>  f_Teacher.TypedDBValue;  set { f_Teacher.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_Teacher { get ; private set; } = new DataStr();

		
		[NotMapped]
		public string? TeacherName { get =>  f_TeacherName.TypedDBValue;  set { f_TeacherName.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_TeacherName { get ; private set; } = new DataStr();

		
		[NotMapped]
		public double? PriceADay { get =>  f_PriceADay.TypedDBValue;  set { f_PriceADay.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataMon f_PriceADay { get ; private set; } = new DataMon();

		
		[NotMapped]
		public bool? Selected { get =>  f_Selected.TypedDBValue;  set { f_Selected.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataBool f_Selected { get ; private set; } = new DataBool();

	}	
}