// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace Courses.Courses.Model
{
	/// <summary>
	/// MMS_Filters
	/// </summary>
	public partial class MMS_Filters : BaseEntity
	{
		public MMS_Filters()
		{
		}

		
		[NotMapped]
		public bool? All { get =>  f_All.TypedDBValue;  set { f_All.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataBool f_All { get ; private set; } = new DataBool();

		
		[NotMapped]
		public bool? Select { get =>  f_Select.TypedDBValue;  set { f_Select.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataBool f_Select { get ; private set; } = new DataBool();

		
		[NotMapped]
		public string? FromTeacher { get =>  f_FromTeacher.TypedDBValue;  set { f_FromTeacher.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_FromTeacher { get ; private set; } = new DataStr();

		
		[NotMapped]
		public string? ToTeacher { get =>  f_ToTeacher.TypedDBValue;  set { f_ToTeacher.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_ToTeacher { get ; private set; } = new DataStr();

		
		[NotMapped]
		public string? FilePath { get =>  f_FilePath.TypedDBValue;  set { f_FilePath.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_FilePath { get ; private set; } = new DataStr();

	}	
}