// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace Courses.Courses.Model
{
	/// <summary>
	/// MMS_Results
	/// </summary>
	public partial class MMS_Results : BaseEntity
	{
		public MMS_Results()
		{
		}

		
		[NotMapped]
		public Int32? CourseID { get =>  f_CourseID.TypedDBValue;  set { f_CourseID.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataLng f_CourseID { get ; private set; } = new DataLng();

		
		[NotMapped]
		public string? CourseDescription { get =>  f_CourseDescription.TypedDBValue;  set { f_CourseDescription.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_CourseDescription { get ; private set; } = new DataStr();

		
		[NotMapped]
		public DateTime? CourseDate { get =>  f_CourseDate.TypedDBValue;  set { f_CourseDate.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataDate f_CourseDate { get ; private set; } = new DataDate();

		
		[NotMapped]
		public int? CourseLevel { get =>  f_CourseLevel.TypedDBValue;  set { f_CourseLevel.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataEnum f_CourseLevel { get ; private set; } = new DataEnum(524353536);

		
		[NotMapped]
		public string? CourseTeacher { get =>  f_CourseTeacher.TypedDBValue;  set { f_CourseTeacher.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_CourseTeacher { get ; private set; } = new DataStr();

		
		[NotMapped]
		public string? TeacherName { get =>  f_TeacherName.TypedDBValue;  set { f_TeacherName.TypedDBValue = value; } }
		[NotMapped]
		public DataStr f_TeacherName { get ; private set; } = new DataStr();

		
		[NotMapped]
		public double? CoursePrice { get =>  f_CoursePrice.TypedDBValue;  set { f_CoursePrice.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataMon f_CoursePrice { get ; private set; } = new DataMon();

		
		[NotMapped]
		public Int16? CourseDays { get =>  f_CourseDays.TypedDBValue;  set { f_CourseDays.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataInt f_CourseDays { get ; private set; } = new DataInt();

		
		[NotMapped]
		public bool? Selected { get =>  f_Selected.TypedDBValue;  set { f_Selected.TypedDBValue = value.Value; } }
		[NotMapped]
		public DataBool f_Selected { get ; private set; } = new DataBool();

	}	
}