// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public sealed class BEDetails_RowPreparedRequest: BaseRequest
    {
        [JsonProperty("rowNumber")]
        public int RowNumber { get; set; }
        [JsonProperty("TotalDays_In")]
        public Int16 TotalDays_In { get; set; }
        [JsonProperty("CourseInfo_Days")]
        public Int16 CourseInfo_Days { get; set; }
        [JsonProperty("CoursesDetails_In")]
        
        public List<MMS_CoursesDetails> CoursesDetails_In { get; set; }
    }

    public sealed class BEDetails_RowPreparedResponse : BaseResponse
    {        
        [JsonProperty("TotalDays_Out")]
        public Int16 TotalDays_Out { get; set; } 
        [JsonProperty("CoursesDetails_Out")]
        
        public MyMagoStudioOneToManyResponse<MMS_CoursesDetails> CoursesDetails_Out { get; set; } = new MyMagoStudioOneToManyResponse<MMS_CoursesDetails>();
    }
}