// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public sealed class Courses_TransactionValidationRequest: BaseRequest
    {
        [JsonProperty("CourseLevel_In")]
        public int CourseLevel_In { get; set; }
        [JsonProperty("CourseInfo_Days_In")]
        public Int16 CourseInfo_Days_In { get; set; }
    }

    public sealed class Courses_TransactionValidationResponse : BaseResponse
    {        
    }
}