// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public sealed class Courses_DataLoadedRequest: BaseRequest
    {
        [JsonProperty("CoursesDetails_In")]
        
        public List<MMS_CoursesDetails> CoursesDetails_In { get; set; }
    }

    public sealed class Courses_DataLoadedResponse : BaseResponse
    {        
        [JsonProperty("totalDays_Out")]
        public Int16 totalDays_Out { get; set; } 
        [JsonProperty("CoursesDetails_Out")]
        
        public MyMagoStudioOneToManyResponse<MMS_CoursesDetails> CoursesDetails_Out { get; set; } = new MyMagoStudioOneToManyResponse<MMS_CoursesDetails>();
    }
}