// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public sealed class Courses_DataInitializedRequest: BaseRequest
    {
    }

    public sealed class Courses_DataInitializedResponse : BaseResponse
    {        
        [JsonProperty("CourseInfo_Days_Out")]
        public Int16 CourseInfo_Days_Out { get; set; } 
    }
}