// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public sealed class TeacherValidatedRequest: BaseRequest
    {
        [JsonProperty("TeacherIN")]
        public MMS_Teachers TeacherIN { get; set; }
        
    }

    public sealed class TeacherValidatedResponse : BaseResponse
    {        
    }
}