// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public sealed class Teacher_ValueChangedRequest: BaseRequest
    {
        [JsonProperty("HKLTeacher_In")]
        public MMS_Teachers HKLTeacher_In { get; set; }
        
    }

    public sealed class Teacher_ValueChangedResponse : BaseResponse
    {        
        [JsonProperty("TeacherComplete_Out")]
        public string TeacherComplete_Out { get; set; } 
    }
}