<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>

	  <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Microarea.Tbf.Model">
      <HintPath>..\..\..\..\dist-libraries\Microarea.Tbf.Model.dll</HintPath>
    </Reference>
    <Reference Include="Microarea.Tbf.Model.AspNet">
      <HintPath>..\..\..\..\dist-libraries\Microarea.Tbf.Model.AspNet.dll</HintPath>
    </Reference>
    <Reference Include="Microarea.Tbf.Model.Interfaces">
      <HintPath>..\..\..\..\dist-libraries\Microarea.Tbf.Model.Interfaces.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
