// DO NOT MODIFY THIS FILE; automatically generated by MMS
using OttieniToken.MOToken.Model;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace OttieniToken.MOToken.DocOttieniToken
{
    public partial class OttieniTokenMOTokenDocOttieniTokenContext : TbDbContext
    {
        public DbSet<MA_Authors> DM_MA_Authors { get; set; }
        public OttieniTokenMOTokenDocOttieniTokenContext(DbType type, string connectionString, string subscription, DbDataContextProduct product, ICheckAddOn checkAddOn = null, ILoggerFactory logFactory = null)
       
            : base(type, connectionString, subscription, product, checkAddOn, logFactory)
        {
        }
    }
}