// DO NOT MODIFY THIS FILE; automatically generated by MMS
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace OttieniToken.MOToken.DocOttieniToken
{
    public partial class OttieniTokenMOTokenDocOttieniToken : MyMagoStudioDocument
    {
        private OttieniTokenMOTokenDocOttieniTokenContext dbContext { get; set; }

        public OttieniTokenMOTokenDocOttieniToken() { }

        public OttieniTokenMOTokenDocOttieniToken(OttieniTokenMOTokenDocOttieniTokenContext dbContext, MyMagoStudioDocumentStatus myMagoStudioDocumentStatus)
            : base(myMagoStudioDocumentStatus)
        { 
            this.dbContext = dbContext;
        }
    }
}