// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPSales.Invoice
{
    public sealed class InvoiceETRequest: BaseRequest
    {
        [JsonProperty("CustSuppIN")]
        public string CustSuppIN { get; set; }
        [JsonProperty("CustSuppTypeIN")]
        public int CustSuppTypeIN { get; set; }
    }

    public sealed class InvoiceETResponse : BaseResponse
    {        
    }
}