// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPSales.Invoice
{
    public sealed class LoadButtonCRequest: BaseRequest
    {
        [JsonProperty("CustSuppIN")]
        public string CustSuppIN { get; set; }
        [JsonProperty("CustSuppTypeIN")]
        public int CustSuppTypeIN { get; set; }
    }

    public sealed class LoadButtonCResponse : BaseResponse
    {        
        [JsonProperty("SaleDocDetailsOUT")]
        
        public MyMagoStudioOneToManyResponse<MA_SaleDocDetail> SaleDocDetailsOUT { get; set; } = new MyMagoStudioOneToManyResponse<MA_SaleDocDetail>();
    }
}