// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPSales.Invoice
{
    public sealed class OpenCoursesCRequest: BaseRequest
    {
    }

    public sealed class OpenCoursesCResponse : BaseResponse
    {        
    }
}