// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace OttieniToken.MOToken.DocOttieniToken
{
    public sealed class ScrivoIlTokenDATAInitRequest: BaseRequest
    {
    }

    public sealed class ScrivoIlTokenDATAInitResponse : BaseResponse
    {        
    }
}