//automatically generated by MMS
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model;
using Microarea.Tbf.Model.API;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using Microarea.Tbf.Model.Interfaces.Database;
using Microarea.Tbf.Model.Interfaces.API;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;

namespace Courses.Courses.Model
{
	/// <summary>
	/// This table contains the details of Sale Documents.
	/// </summary>
	public partial class MA_SaleDocDetailObj  : BaseEntity
	{
		//add your code here
	}	

	public partial class MA_SaleDocDetail : MA_SaleDocDetailObj
	{
		//add your code here
	}
}