// DO NOT MODIFY THIS FILE; automatically generated by MMS
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace CoursesCourses.GenerateNewCourses
{
    public partial class CoursesCoursesGenerateNewCourses : MyMagoStudioDocument
    {
        private CoursesCoursesGenerateNewCoursesContext dbContext { get; set; }

        public CoursesCoursesGenerateNewCourses() { }

        public CoursesCoursesGenerateNewCourses(CoursesCoursesGenerateNewCoursesContext dbContext, MyMagoStudioDocumentStatus myMagoStudioDocumentStatus)
            : base(myMagoStudioDocumentStatus)
        { 
            this.dbContext = dbContext;
        }
    }
}