// DO NOT MODIFY THIS FILE; automatically generated by MMS
using Courses.Courses.Model;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace CoursesCourses.GenerateNewCourses
{
    public partial class CoursesCoursesGenerateNewCoursesContext : TbDbContext
    {
        public DbSet<MMS_Courses> DM_MMS_Courses { get; set; }
        public DbSet<MMS_Teachers> DM_MMS_Teachers { get; set; }
        public DbSet<MMS_CoursesInfo> DM_MMS_CoursesInfo { get; set; }
        public DbSet<MMS_CoursesDetails> DM_MMS_CoursesDetails { get; set; }
        public CoursesCoursesGenerateNewCoursesContext(DbType type, string connectionString, string subscription, DbDataContextProduct product, ICheckAddOn checkAddOn = null, ILoggerFactory logFactory = null)
       
            : base(type, connectionString, subscription, product, checkAddOn, logFactory)
        {
        }
    }
}