	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace Courses.Courses.Model
{
	
	/// <summary>
	/// tabella slave 1a1
	/// </summary>
	public partial class MMS_CoursesInfoObj  : BaseEntity
	{
		public MMS_CoursesInfoObj()
		{
		}

		/// <summary>
		/// codice corso
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 CourseID { get =>  f_CourseID.TypedDBValue;  set { f_CourseID.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_CourseID { get ; private set; } = new DataLng();



		/// <summary>
		/// durata del corso
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? CourseDays { get =>  f_CourseDays.TypedDBValue;  set { f_CourseDays.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_CourseDays { get ; private set; } = new DataInt();



		/// <summary>
		/// docente corso
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? CourseTeacher { get =>  f_CourseTeacher.TypedDBValue;  set { f_CourseTeacher.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_CourseTeacher { get ; private set; } = new DataStr();



		/// <summary>
		/// prezzo corso
		/// 	
		/// DefaultValue: 0.0
		/// </summary>

		public double? CoursePrice { get =>  f_CoursePrice.TypedDBValue;  set { f_CoursePrice.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_CoursePrice { get ; private set; } = new DataMon();




	}	

	[Table("MMS_CoursesInfo")]
    [TbEntityTypeConfiguration(typeof(MMS_CoursesInfoConfiguration))]
	public partial class MMS_CoursesInfo : MMS_CoursesInfoObj
	{
		public MMS_CoursesInfo()
			:base()
		{
		}
	}

	public sealed class MMS_CoursesInfoConfiguration : MMS_CoursesInfoConfiguration<MMS_CoursesInfo>
	{
		public MMS_CoursesInfoConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MMS_CoursesInfo> entity)
		{
			base.Configure(entity);
		}
	}

	public class MMS_CoursesInfoConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MMS_CoursesInfoObj
    {
        public MMS_CoursesInfoConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => e.CourseID).HasName("PK_MMS_CoursesInfo").IsClustered(false);
		#else
			entity.HasKey(e => e.CourseID).HasName("PK_MMS_CoursesInfo").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.CourseID).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.CourseDays).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CourseTeacher).HasMaxLength(6).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CoursePrice).HasDefaultValueSql("('0.0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.CourseID).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.CourseDays).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CourseTeacher).HasMaxLength(6).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CoursePrice).HasDefaultValueSql("('0.0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MMS_CoursesInfo
	/// </summary>
	public class MMS_CoursesInfoAggregate<TContext> : BaseTbAggregate<TContext, MMS_CoursesInfo>
                                                                            where TContext : TbDbContext
    {
        public MMS_CoursesInfoAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MMS_CoursesInfo> Query(Int32 courseID)
			=> EntityDbSet.Where(x => x.CourseID == courseID);

		#region SyncMethods 
		/// <summary>
		/// Return MMS_CoursesInfo based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetMMS_CoursesInfo<TResult>(Int32 courseID,
		                                       Expression<Func<MMS_CoursesInfo, TResult>> selector, TResult @default = default)		
			=> Result(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of MMS_CoursesInfo based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetMMS_CoursesInfoTbResult<TResult>(Int32 courseID,
		                                                          Expression<Func<MMS_CoursesInfo, TResult>> selector, TResult @default = default)
			=> TbResult(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return MMS_CoursesInfo based on primary key parameters default of MMS_CoursesInfo if not found
		/// </summary>
        /// <remarks>Prefered to use GetMMS_CoursesInfo with selector parameter</remarks>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MMS_CoursesInfo or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetMMS_CoursesInfo with selector parameter")]
        public MMS_CoursesInfo GetMMS_CoursesInfo(Int32 courseID,
												   MMS_CoursesInfo @default = default)
			=> Result(Query(courseID), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return MMS_CoursesInfo based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetMMS_CoursesInfoAsync<TResult>(Int32 courseID,
		                                       Expression<Func<MMS_CoursesInfo, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of MMS_CoursesInfo based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetMMS_CoursesInfoTbResultAsync<TResult>(Int32 courseID,
		                                                          Expression<Func<MMS_CoursesInfo, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(courseID).Select(selector), @default);

		/// <summary>
		/// Return MMS_CoursesInfo based on primary key parameters default of MMS_CoursesInfo if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetMMS_CoursesInfo with selector parameter</remarks>
		
		/// <param name="courseID">codice corso</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MMS_CoursesInfo or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetMMS_CoursesInfo with selector parameter")]
        public Task<MMS_CoursesInfo> GetMMS_CoursesInfoAsync(Int32 courseID,
												   MMS_CoursesInfo @default = default)
			=> ResultAsync(Query(courseID), @default);

		#endregion 
		
    }

}