// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace CoursesCourses.DuplicateCourses
{
    public sealed class uploadFileRequest: BaseRequest
    {
        [JsonProperty("Filters_IN")]
        public MMS_Filters Filters_IN { get; set; }
        
    }

    public sealed class uploadFileResponse : BaseResponse
    {        
    }
}