// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPSales.Invoice
{
    public sealed class Customer_ValueChangedRequest: BaseRequest
    {
    }

    public sealed class Customer_ValueChangedResponse : BaseResponse
    {        
        [JsonProperty("Details_Out")]
        
        public MyMagoStudioOneToManyResponse<MA_SaleDocDetail> Details_Out { get; set; } = new MyMagoStudioOneToManyResponse<MA_SaleDocDetail>();
    }
}