// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPSales.Invoice
{
    public sealed class LoadCourses_ClickedRequest: BaseRequest
    {
        [JsonProperty("CustSuppType_In")]
        public int CustSuppType_In { get; set; }
        [JsonProperty("CustSupp_In")]
        public string CustSupp_In { get; set; }
    }

    public sealed class LoadCourses_ClickedResponse : BaseResponse
    {        
        [JsonProperty("Detail_Out")]
        
        public MyMagoStudioOneToManyResponse<MA_SaleDocDetail> Detail_Out { get; set; } = new MyMagoStudioOneToManyResponse<MA_SaleDocDetail>();
    }
}