// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPCompany.ActivityCodes
{
    public sealed class Description_ValueChangedRequest: BaseRequest
    {
        [JsonProperty("Description_In")]
        public string Description_In { get; set; }
    }

    public sealed class Description_ValueChangedResponse : BaseResponse
    {        
        [JsonProperty("Description_Out")]
        public string Description_Out { get; set; } 
    }
}