// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using CoursesCourses.GenerateNewCourses;
using Microarea.Interfaces;
using Newtonsoft.Json.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.Extensions.Primitives;
using Microarea.Tbf.Model.MyMagoStudioBase;
using Microarea.Generic.DiagnosticManager;
using System.Collections.Generic;

namespace Courses.Courses.Controllers
{
    [ApiController]
    [Route("Courses-Courses-service/[controller]")]
    [ApiExplorerSettings(GroupName = "CoursesCoursesGenerateNewCourses")]
    public class CoursesCoursesGenerateNewCoursesController : MyMagoStudioController<CoursesCoursesGenerateNewCourses, CoursesCoursesGenerateNewCoursesContext>
    {
        public CoursesCoursesGenerateNewCoursesController(IServiceProvider serviceProvider) : base(serviceProvider) { }

        /// <summary>
        /// Complete your business logic for extract data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("ExtractData")]
        public async Task<IActionResult> ExtractData([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<ExtractDataRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.ExtractData(req as ExtractDataRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as ExtractDataResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for elaborate your data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("BatchExecute")]
        public async Task<IActionResult> BatchExecute([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<BatchExecuteRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.BatchExecute(req as BatchExecuteRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as BatchExecuteResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for button click
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("ManyTestsOnClick")]
        public async Task<IActionResult> ManyTestsOnClick([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<ManyTestsOnClickRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.ManyTestsOnClick(req as ManyTestsOnClickRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as ManyTestsOnClickResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for validate your data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("FiltersValidate")]
        public async Task<IActionResult> FiltersValidate([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<FiltersValidateRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.FiltersValidate(req as FiltersValidateRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as FiltersValidateResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
    } 
}