// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using ERPSales.Invoice;
using Microarea.Interfaces;
using Newtonsoft.Json.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.Extensions.Primitives;
using Microarea.Tbf.Model.MyMagoStudioBase;
using Microarea.Generic.DiagnosticManager;
using System.Collections.Generic;

namespace Courses.Courses.Controllers
{
    [ApiController]
    [Route("Courses-Courses-service/[controller]")]
    [ApiExplorerSettings(GroupName = "ERPSalesInvoice")]
    public class ERPSalesInvoiceController : MyMagoStudioController<ERPSalesInvoice, ERPSalesInvoiceContext>
    {
        public ERPSalesInvoiceController(IServiceProvider serviceProvider) : base(serviceProvider) { }

        /// <summary>
        /// Complete your business logic for click on buttont
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("LoadCourses_CanDoClick")]
        public async Task<IActionResult> LoadCourses_CanDoClick([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<LoadCourses_CanDoClickRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.LoadCourses_CanDoClick(req as LoadCourses_CanDoClickRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as LoadCourses_CanDoClickResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for button click
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("LoadCourses_Clicked")]
        public async Task<IActionResult> LoadCourses_Clicked([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<LoadCourses_ClickedRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.LoadCourses_Clicked(req as LoadCourses_ClickedRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as LoadCourses_ClickedResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for manage data and/or data's status (visible/readobly)
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("Customer_ValueChanged")]
        public async Task<IActionResult> Customer_ValueChanged([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<Customer_ValueChangedRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.Customer_ValueChanged(req as Customer_ValueChangedRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as Customer_ValueChangedResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic to save your data in an extra transaction
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("Invoice_ExtraTransacting")]
        public async Task<IActionResult> Invoice_ExtraTransacting([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<Invoice_ExtraTransactingRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.Invoice_ExtraTransacting(req as Invoice_ExtraTransactingRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as Invoice_ExtraTransactingResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
    } 
}