// DO NOT MODIFY THIS FILE; automatically generated by MMS
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPCompany.ActivityCodes
{
    public partial class ERPCompanyActivityCodes : MyMagoStudioDocument
    {
        private ERPCompanyActivityCodesContext dbContext { get; set; }

        public ERPCompanyActivityCodes() { }

        public ERPCompanyActivityCodes(ERPCompanyActivityCodesContext dbContext, MyMagoStudioDocumentStatus myMagoStudioDocumentStatus)
            : base(myMagoStudioDocumentStatus)
        { 
            this.dbContext = dbContext;
        }
    }
}