// DO NOT MODIFY THIS FILE; automatically generated by MMS
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace ERPSales.Invoice
{
    public partial class ERPSalesInvoice : MyMagoStudioDocument
    {
        private ERPSalesInvoiceContext dbContext { get; set; }

        public ERPSalesInvoice() { }

        public ERPSalesInvoice(ERPSalesInvoiceContext dbContext, MyMagoStudioDocumentStatus myMagoStudioDocumentStatus)
            : base(myMagoStudioDocumentStatus)
        { 
            this.dbContext = dbContext;
        }
    }
}