	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	
	/// <summary>
	/// This table contains the Authors.
	/// </summary>
	public partial class MA_AuthorsObj  : MasterEntity
	{
		public MA_AuthorsObj()
		{
		}

		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: ""
		/// </summary>
		[TbPrimaryKey(0)]

		public string AuthorCode { get =>  f_AuthorCode.TypedDBValue;  set { f_AuthorCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_AuthorCode { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Description { get =>  f_Description.TypedDBValue;  set { f_Description.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Description { get ; private set; } = new DataStr();




	}	

	[Table("MA_Authors")]
    [TbEntityTypeConfiguration(typeof(MA_AuthorsConfiguration))]
	public partial class MA_Authors : MA_AuthorsObj
	{
		public MA_Authors()
			:base()
		{
		}
	}

	public sealed class MA_AuthorsConfiguration : MA_AuthorsConfiguration<MA_Authors>
	{
		public MA_AuthorsConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_Authors> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_AuthorsConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_AuthorsObj
    {
        public MA_AuthorsConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => e.AuthorCode).HasName("PK_Authors").IsClustered(false);
		#else
			entity.HasKey(e => e.AuthorCode).HasName("PK_Authors").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.AuthorCode).HasMaxLength(8).IsRequired().HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Description).HasMaxLength(64).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbGuid).IsRequired().HasDefaultValueSql("NEWID()");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.AuthorCode).HasMaxLength(8).IsRequired().HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Description).HasMaxLength(64).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbGuid).IsRequired().HasDefaultValueSql("uuid_generate_v1()");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_Authors
	/// </summary>
	public class AuthorsAggregate<TContext> : BaseTbAggregate<TContext, MA_Authors>
                                                                            where TContext : TbDbContext
    {
        public AuthorsAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_Authors> Query(string authorCode)
			=> EntityDbSet.Where(x => x.AuthorCode == authorCode);

		#region SyncMethods 
		/// <summary>
		/// Return Authors based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="authorCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetAuthors<TResult>(string authorCode,
		                                       Expression<Func<MA_Authors, TResult>> selector, TResult @default = default)		
			=> Result(Query(authorCode).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of Authors based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="authorCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetAuthorsTbResult<TResult>(string authorCode,
		                                                          Expression<Func<MA_Authors, TResult>> selector, TResult @default = default)
			=> TbResult(Query(authorCode).Select(selector), @default);

		/// <summary>
		/// Return Authors based on primary key parameters default of MA_Authors if not found
		/// </summary>
        /// <remarks>Prefered to use GetAuthors with selector parameter</remarks>
		
		/// <param name="authorCode"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_Authors or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetAuthors with selector parameter")]
        public MA_Authors GetAuthors(string authorCode,
												   MA_Authors @default = default)
			=> Result(Query(authorCode), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return Authors based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="authorCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetAuthorsAsync<TResult>(string authorCode,
		                                       Expression<Func<MA_Authors, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(authorCode).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of Authors based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="authorCode"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetAuthorsTbResultAsync<TResult>(string authorCode,
		                                                          Expression<Func<MA_Authors, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(authorCode).Select(selector), @default);

		/// <summary>
		/// Return Authors based on primary key parameters default of MA_Authors if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetAuthors with selector parameter</remarks>
		
		/// <param name="authorCode"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_Authors or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetAuthors with selector parameter")]
        public Task<MA_Authors> GetAuthorsAsync(string authorCode,
												   MA_Authors @default = default)
			=> ResultAsync(Query(authorCode), @default);

		#endregion 
		
    }

}