	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	[TbCompanyIdColumn("TBCompanyID")]
	[TbRowSecurityAccessType("public_access")]	
	/// <summary>
	/// 
	/// </summary>
	public partial class MA_SaleOrdDetailVarObj  : BaseEntity
	{
		public MA_SaleOrdDetailVarObj()
		{
		}

		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(1)]

		public Int32 SubId { get =>  f_SubId.TypedDBValue;  set { f_SubId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SubId { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? SaleOrdSubId { get =>  f_SaleOrdSubId.TypedDBValue;  set { f_SaleOrdSubId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdSubId { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? VariantSubId { get =>  f_VariantSubId.TypedDBValue;  set { f_VariantSubId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_VariantSubId { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? VariantCode { get =>  f_VariantCode.TypedDBValue;  set { f_VariantCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_VariantCode { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Qty { get =>  f_Qty.TypedDBValue;  set { f_Qty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_Qty { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DeliveredQty { get =>  f_DeliveredQty.TypedDBValue;  set { f_DeliveredQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_DeliveredQty { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? InvoicedQty { get =>  f_InvoicedQty.TypedDBValue;  set { f_InvoicedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_InvoicedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? ReceiptQty { get =>  f_ReceiptQty.TypedDBValue;  set { f_ReceiptQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_ReceiptQty { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Delivered { get =>  f_Delivered.TypedDBValue;  set { f_Delivered.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Delivered { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Invoiced { get =>  f_Invoiced.TypedDBValue;  set { f_Invoiced.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Invoiced { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Receipt { get =>  f_Receipt.TypedDBValue;  set { f_Receipt.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Receipt { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Picked { get =>  f_Picked.TypedDBValue;  set { f_Picked.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Picked { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PickedQty { get =>  f_PickedQty.TypedDBValue;  set { f_PickedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PickedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PickedAndDeliveredQty { get =>  f_PickedAndDeliveredQty.TypedDBValue;  set { f_PickedAndDeliveredQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PickedAndDeliveredQty { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? UnitValue { get =>  f_UnitValue.TypedDBValue;  set { f_UnitValue.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_UnitValue { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? DiscountFormula { get =>  f_DiscountFormula.TypedDBValue;  set { f_DiscountFormula.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_DiscountFormula { get ; private set; } = new DataStr();



		/// <summary>
		/// Cross Reference type
		/// 	
		/// DefaultValue: 27066368
		/// </summary>

		public int? CRRefType { get =>  f_CRRefType.TypedDBValue;  set { f_CRRefType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_CRRefType { get ; private set; } = new DataEnum(27066368);



		/// <summary>
		/// Cross Reference identifier
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? CRRefID { get =>  f_CRRefID.TypedDBValue;  set { f_CRRefID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_CRRefID { get ; private set; } = new DataLng();



		/// <summary>
		/// Cross Reference sub-identifier
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? CRRefVariantSubID { get =>  f_CRRefVariantSubID.TypedDBValue;  set { f_CRRefVariantSubID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_CRRefVariantSubID { get ; private set; } = new DataLng();



		/// <summary>
		/// Field used by CGM
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? TBCompanyID { get =>  f_TBCompanyID.TypedDBValue;  set { f_TBCompanyID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_TBCompanyID { get ; private set; } = new DataLng();



		/// <summary>
		/// Cancelled
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Cancelled { get =>  f_Cancelled.TypedDBValue;  set { f_Cancelled.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Cancelled { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates that the line has been completely preshipped.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PreShipped { get =>  f_PreShipped.TypedDBValue;  set { f_PreShipped.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PreShipped { get ; private set; } = new DataBool();



		/// <summary>
		/// Preshipped quantity. It is automatically updated fulfilling the sale order in preshipping.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public double? PreShippedQty { get =>  f_PreShippedQty.TypedDBValue;  set { f_PreShippedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PreShippedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Field for internal use.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public double? PreShippedAndDeliveredQty { get =>  f_PreShippedAndDeliveredQty.TypedDBValue;  set { f_PreShippedAndDeliveredQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PreShippedAndDeliveredQty { get ; private set; } = new DataQty();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Lot { get =>  f_Lot.TypedDBValue;  set { f_Lot.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Lot { get ; private set; } = new DataStr();




	}	

	[Table("MA_SaleOrdDetailVar")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdDetailVarConfiguration))]
	public partial class MA_SaleOrdDetailVar : MA_SaleOrdDetailVarObj
	{
		public MA_SaleOrdDetailVar()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdDetailVarConfiguration : MA_SaleOrdDetailVarConfiguration<MA_SaleOrdDetailVar>
	{
		public MA_SaleOrdDetailVarConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdDetailVar> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdDetailVarConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdDetailVarObj
    {
        public MA_SaleOrdDetailVarConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => new { e.SaleOrdId,e.SubId }).HasName("PK_SaleOrdDetVar").IsClustered(false);
		#else
			entity.HasKey(e => new { e.SaleOrdId,e.SubId }).HasName("PK_SaleOrdDetVar").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SubId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SaleOrdSubId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.VariantSubId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.VariantCode).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Qty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.InvoicedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ReceiptQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Delivered).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Invoiced).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Receipt).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Picked).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PickedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PickedAndDeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountFormula).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CRRefType).HasDefaultValueSql("(27066368)")  ;
					entity.Property(e => e.CRRefID).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CRRefVariantSubID).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.TBCompanyID).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Cancelled).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PreShipped).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PreShippedQty).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PreShippedAndDeliveredQty).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Lot).HasMaxLength(16).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SubId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SaleOrdSubId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.VariantSubId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.VariantCode).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Qty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.InvoicedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ReceiptQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Delivered).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Invoiced).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Receipt).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Picked).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PickedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PickedAndDeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountFormula).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CRRefType).HasDefaultValueSql("(27066368)")  ;
					entity.Property(e => e.CRRefID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CRRefVariantSubID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.TBCompanyID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Cancelled).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PreShipped).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PreShippedQty).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PreShippedAndDeliveredQty).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Lot).HasMaxLength(16).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdDetailVar
	/// </summary>
	public class SaleOrdDetailVarAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdDetailVar>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdDetailVarAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdDetailVar> Query(Int32 saleOrdId,Int32 subId)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId && x.SubId == subId);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdDetailVar based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="subId"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdDetailVar<TResult>(Int32 saleOrdId,Int32 subId,
		                                       Expression<Func<MA_SaleOrdDetailVar, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId,subId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdDetailVar based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="subId"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdDetailVarTbResult<TResult>(Int32 saleOrdId,Int32 subId,
		                                                          Expression<Func<MA_SaleOrdDetailVar, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId,subId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdDetailVar based on primary key parameters default of MA_SaleOrdDetailVar if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdDetailVar with selector parameter</remarks>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="subId"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdDetailVar or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdDetailVar with selector parameter")]
        public MA_SaleOrdDetailVar GetSaleOrdDetailVar(Int32 saleOrdId,Int32 subId,
												   MA_SaleOrdDetailVar @default = default)
			=> Result(Query(saleOrdId,subId), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdDetailVar based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="subId"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdDetailVarAsync<TResult>(Int32 saleOrdId,Int32 subId,
		                                       Expression<Func<MA_SaleOrdDetailVar, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId,subId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdDetailVar based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="subId"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdDetailVarTbResultAsync<TResult>(Int32 saleOrdId,Int32 subId,
		                                                          Expression<Func<MA_SaleOrdDetailVar, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId,subId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdDetailVar based on primary key parameters default of MA_SaleOrdDetailVar if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdDetailVar with selector parameter</remarks>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="subId"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdDetailVar or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdDetailVar with selector parameter")]
        public Task<MA_SaleOrdDetailVar> GetSaleOrdDetailVarAsync(Int32 saleOrdId,Int32 subId,
												   MA_SaleOrdDetailVar @default = default)
			=> ResultAsync(Query(saleOrdId,subId), @default);

		#endregion 
		
    }

}