	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	[TbCompanyIdColumn("TBCompanyID")]
	[TbRowSecurityAccessType("public_access")]	
	/// <summary>
	/// The table contains data relevant to the shipment of goods. It is a buffered of the table MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdShippingObj  : BaseEntity
	{
		public MA_SaleOrdShippingObj()
		{
		}

		/// <summary>
		/// It indicates if the port is free or not. In Mago.Net automatisms connected to the Free Port are relevant to the only Port code set in the Sale default codes. It can be automatically set according to the customer master data.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Port { get =>  f_Port.TypedDBValue;  set { f_Port.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Port { get ; private set; } = new DataStr();



		/// <summary>
		/// It indicates who is the responsible of the shipment. It can be automatically proposed according to the customer master data.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Shipping { get =>  f_Shipping.TypedDBValue;  set { f_Shipping.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Shipping { get ; private set; } = new DataStr();



		/// <summary>
		/// It specifies the packing type of the goods. It can be automatically proposed according to the customer master data.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Package { get =>  f_Package.TypedDBValue;  set { f_Package.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Package { get ; private set; } = new DataStr();



		/// <summary>
		/// It indicates the goods appearance.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Appearance { get =>  f_Appearance.TypedDBValue;  set { f_Appearance.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Appearance { get ; private set; } = new DataStr();



		/// <summary>
		/// Number of packs. It can be automatically calculated as sum of the number of packs in the lines (field NoOfPacks of the table MA_SaleOrdDetails).
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? NoOfPacks { get =>  f_NoOfPacks.TypedDBValue;  set { f_NoOfPacks.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_NoOfPacks { get ; private set; } = new DataInt();



		/// <summary>
		/// Net weight. It can be automatically calculated as sum of the net weights in the lines (field NetWeight in the table MA_SaleOrdDetails).
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? NetWeight { get =>  f_NetWeight.TypedDBValue;  set { f_NetWeight.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDbl f_NetWeight { get ; private set; } = new DataDbl();



		/// <summary>
		/// Gross weight. It can be automatically calculated as sum of the gross weights in the lines (field GrossWeight in the table MA_SaleOrdDetails).
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? GrossWeight { get =>  f_GrossWeight.TypedDBValue;  set { f_GrossWeight.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDbl f_GrossWeight { get ; private set; } = new DataDbl();



		/// <summary>
		/// Gross volume. It can be automatically calculated as sum of the gross weights in the lines (field GrossVolume in the table MA_SaleOrdDetails).
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? GrossVolume { get =>  f_GrossVolume.TypedDBValue;  set { f_GrossVolume.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDbl f_GrossVolume { get ; private set; } = new DataDbl();



		/// <summary>
		/// First carrier. It can be automatically set according to the customer master data. According to the settings it can determine the shipping charges calculation.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Carrier1 { get =>  f_Carrier1.TypedDBValue;  set { f_Carrier1.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Carrier1 { get ; private set; } = new DataStr();



		/// <summary>
		/// Second carrier. It can be automatically set according to the customer master data.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Carrier2 { get =>  f_Carrier2.TypedDBValue;  set { f_Carrier2.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Carrier2 { get ; private set; } = new DataStr();



		/// <summary>
		/// Third carrier. It can be automatically set according to the customer master data.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Carrier3 { get =>  f_Carrier3.TypedDBValue;  set { f_Carrier3.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Carrier3 { get ; private set; } = new DataStr();



		/// <summary>
		/// Customer branch office where the goods will be sent. It is automatically proposed according to the customer master data and it is possible to select one among those provided for that customer.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ShipToAddress { get =>  f_ShipToAddress.TypedDBValue;  set { f_ShipToAddress.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ShipToAddress { get ; private set; } = new DataStr();



		/// <summary>
		/// It links this data to the relevant sale order.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// It indicates how the goods will be shipped. It can be automatically set according to the customer master data.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Transport { get =>  f_Transport.TypedDBValue;  set { f_Transport.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Transport { get ; private set; } = new DataStr();



		/// <summary>
		/// It indicates if the number of packs has been manually entered or automatically calculated. It is proposed according to the parameters.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoOfPacksIsAuto { get =>  f_NoOfPacksIsAuto.TypedDBValue;  set { f_NoOfPacksIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoOfPacksIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the net weight has been manually entered or automatically calculated. It is proposed according to the parameters.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NetWeightIsAuto { get =>  f_NetWeightIsAuto.TypedDBValue;  set { f_NetWeightIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NetWeightIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the gross weight has been manually entered or automatically calculated. It is proposed according to the parameters.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? GrossWeightIsAuto { get =>  f_GrossWeightIsAuto.TypedDBValue;  set { f_GrossWeightIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_GrossWeightIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the gross volume has been manually entered or automatically calculated. It is proposed according to the parameters.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? GrossVolumeIsAuto { get =>  f_GrossVolumeIsAuto.TypedDBValue;  set { f_GrossVolumeIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_GrossVolumeIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the port set in sale orders must be maintained in the following documents or reassigned according to the relevant parameters. It is assigned on the basis of the parameters.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? UseOrderPort { get =>  f_UseOrderPort.TypedDBValue;  set { f_UseOrderPort.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_UseOrderPort { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the port is manually entered or proposed according to the customer master data.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PortAuto { get =>  f_PortAuto.TypedDBValue;  set { f_PortAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PortAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 30670851
		/// </summary>

		public int? PickUpPointType { get =>  f_PickUpPointType.TypedDBValue;  set { f_PickUpPointType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_PickUpPointType { get ; private set; } = new DataEnum(30670851);



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? PickUpPointCode { get =>  f_PickUpPointCode.TypedDBValue;  set { f_PickUpPointCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_PickUpPointCode { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? PickUpPointBranch { get =>  f_PickUpPointBranch.TypedDBValue;  set { f_PickUpPointBranch.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_PickUpPointBranch { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 30736388
		/// </summary>

		public int? DeliveryToType { get =>  f_DeliveryToType.TypedDBValue;  set { f_DeliveryToType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_DeliveryToType { get ; private set; } = new DataEnum(30736388);



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? DeliveryToCode { get =>  f_DeliveryToCode.TypedDBValue;  set { f_DeliveryToCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_DeliveryToCode { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? DeliveryToBranch { get =>  f_DeliveryToBranch.TypedDBValue;  set { f_DeliveryToBranch.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_DeliveryToBranch { get ; private set; } = new DataStr();



		/// <summary>
		/// Field used by CGM
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? TBCompanyID { get =>  f_TBCompanyID.TypedDBValue;  set { f_TBCompanyID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_TBCompanyID { get ; private set; } = new DataLng();



		/// <summary>
		/// Store
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Store { get =>  f_Store.TypedDBValue;  set { f_Store.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Store { get ; private set; } = new DataStr();




	}	

	[Table("MA_SaleOrdShipping")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdShippingConfiguration))]
	public partial class MA_SaleOrdShipping : MA_SaleOrdShippingObj
	{
		public MA_SaleOrdShipping()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdShippingConfiguration : MA_SaleOrdShippingConfiguration<MA_SaleOrdShipping>
	{
		public MA_SaleOrdShippingConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdShipping> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdShippingConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdShippingObj
    {
        public MA_SaleOrdShippingConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => e.SaleOrdId).HasName("PK_SaleOrdShipping").IsClustered(false);
		#else
			entity.HasKey(e => e.SaleOrdId).HasName("PK_SaleOrdShipping").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.Port).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Shipping).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Package).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Appearance).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NoOfPacks).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.NetWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GrossWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GrossVolume).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Carrier1).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Carrier2).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Carrier3).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ShipToAddress).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Transport).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NoOfPacksIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.NetWeightIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.GrossWeightIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.GrossVolumeIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.UseOrderPort).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PortAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PickUpPointType).HasDefaultValueSql("(30670851)")  ;
					entity.Property(e => e.PickUpPointCode).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.PickUpPointBranch).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DeliveryToType).HasDefaultValueSql("(30736388)")  ;
					entity.Property(e => e.DeliveryToCode).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DeliveryToBranch).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.TBCompanyID).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Store).HasMaxLength(8).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.Port).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Shipping).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Package).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Appearance).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NoOfPacks).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.NetWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GrossWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GrossVolume).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Carrier1).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Carrier2).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Carrier3).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ShipToAddress).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Transport).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NoOfPacksIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.NetWeightIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.GrossWeightIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.GrossVolumeIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.UseOrderPort).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PortAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PickUpPointType).HasDefaultValueSql("(30670851)")  ;
					entity.Property(e => e.PickUpPointCode).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.PickUpPointBranch).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DeliveryToType).HasDefaultValueSql("(30736388)")  ;
					entity.Property(e => e.DeliveryToCode).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DeliveryToBranch).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.TBCompanyID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Store).HasMaxLength(8).HasDefaultValueSql("('')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdShipping
	/// </summary>
	public class SaleOrdShippingAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdShipping>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdShippingAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdShipping> Query(Int32 saleOrdId)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdShipping based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links this data to the relevant sale order.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdShipping<TResult>(Int32 saleOrdId,
		                                       Expression<Func<MA_SaleOrdShipping, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdShipping based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links this data to the relevant sale order.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdShippingTbResult<TResult>(Int32 saleOrdId,
		                                                          Expression<Func<MA_SaleOrdShipping, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdShipping based on primary key parameters default of MA_SaleOrdShipping if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdShipping with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links this data to the relevant sale order.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdShipping or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdShipping with selector parameter")]
        public MA_SaleOrdShipping GetSaleOrdShipping(Int32 saleOrdId,
												   MA_SaleOrdShipping @default = default)
			=> Result(Query(saleOrdId), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdShipping based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links this data to the relevant sale order.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdShippingAsync<TResult>(Int32 saleOrdId,
		                                       Expression<Func<MA_SaleOrdShipping, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdShipping based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links this data to the relevant sale order.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdShippingTbResultAsync<TResult>(Int32 saleOrdId,
		                                                          Expression<Func<MA_SaleOrdShipping, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdShipping based on primary key parameters default of MA_SaleOrdShipping if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdShipping with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links this data to the relevant sale order.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdShipping or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdShipping with selector parameter")]
        public Task<MA_SaleOrdShipping> GetSaleOrdShippingAsync(Int32 saleOrdId,
												   MA_SaleOrdShipping @default = default)
			=> ResultAsync(Query(saleOrdId), @default);

		#endregion 
		
    }

}