	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	[TbCompanyIdColumn("TBCompanyID")]
	[TbRowSecurityAccessType("public_access")]	
	/// <summary>
	/// The table contains Sale order payment schedules. It is used only when a customized payment is set (MA_SaleOrd NonStandardPayment). It is a slave buffered of the table MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdPymtSchedObj  : BaseEntity
	{
		public MA_SaleOrdPymtSchedObj()
		{
		}

		/// <summary>
		/// Progressive installment number.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(1)]

		public Int16 InstallmentNo { get =>  f_InstallmentNo.TypedDBValue;  set { f_InstallmentNo.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_InstallmentNo { get ; private set; } = new DataInt();



		/// <summary>
		/// Installment type. Automatically proposed according to the payment term in the document head.
		/// 	
		/// DefaultValue: 2686977
		/// </summary>

		public int? InstallmentType { get =>  f_InstallmentType.TypedDBValue;  set { f_InstallmentType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_InstallmentType { get ; private set; } = new DataEnum(2686977);



		/// <summary>
		/// Number of days from the date from which the installment is calculated (InstallmStartDate).
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? DueDateDays { get =>  f_DueDateDays.TypedDBValue;  set { f_DueDateDays.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_DueDateDays { get ; private set; } = new DataInt();



		/// <summary>
		/// Installment taxable amount.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Amount { get =>  f_Amount.TypedDBValue;  set { f_Amount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_Amount { get ; private set; } = new DataMon();



		/// <summary>
		/// Installment tax amount.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TaxAmount { get =>  f_TaxAmount.TypedDBValue;  set { f_TaxAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TaxAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// It identifies univocally the sale order to which installments are referred.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// It indicates from which date installments must be calculated.
		/// 	
		/// DefaultValue: 7602177
		/// </summary>

		public int? InstallmStartDate { get =>  f_InstallmStartDate.TypedDBValue;  set { f_InstallmStartDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_InstallmStartDate { get ; private set; } = new DataEnum(7602177);



		/// <summary>
		/// Field used by CGM
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? TBCompanyID { get =>  f_TBCompanyID.TypedDBValue;  set { f_TBCompanyID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_TBCompanyID { get ; private set; } = new DataLng();




	}	

	[Table("MA_SaleOrdPymtSched")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdPymtSchedConfiguration))]
	public partial class MA_SaleOrdPymtSched : MA_SaleOrdPymtSchedObj
	{
		public MA_SaleOrdPymtSched()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdPymtSchedConfiguration : MA_SaleOrdPymtSchedConfiguration<MA_SaleOrdPymtSched>
	{
		public MA_SaleOrdPymtSchedConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdPymtSched> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdPymtSchedConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdPymtSchedObj
    {
        public MA_SaleOrdPymtSchedConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => new { e.SaleOrdId,e.InstallmentNo }).HasName("PK_SaleOrdPymtSched").IsClustered(false);
		#else
			entity.HasKey(e => new { e.SaleOrdId,e.InstallmentNo }).HasName("PK_SaleOrdPymtSched").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.InstallmentNo).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.InstallmentType).HasDefaultValueSql("(2686977)")  ;
					entity.Property(e => e.DueDateDays).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Amount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.InstallmStartDate).HasDefaultValueSql("(7602177)")  ;
					entity.Property(e => e.TBCompanyID).HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.InstallmentNo).HasColumnType("smallint").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.InstallmentType).HasDefaultValueSql("(2686977)")  ;
					entity.Property(e => e.DueDateDays).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Amount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.InstallmStartDate).HasDefaultValueSql("(7602177)")  ;
					entity.Property(e => e.TBCompanyID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdPymtSched
	/// </summary>
	public class SaleOrdPymtSchedAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdPymtSched>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdPymtSchedAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdPymtSched> Query(Int32 saleOrdId,Int16 installmentNo)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId && x.InstallmentNo == installmentNo);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdPymtSched based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It identifies univocally the sale order to which installments are referred.</param>
		
		/// <param name="installmentNo">Progressive installment number.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdPymtSched<TResult>(Int32 saleOrdId,Int16 installmentNo,
		                                       Expression<Func<MA_SaleOrdPymtSched, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId,installmentNo).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdPymtSched based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It identifies univocally the sale order to which installments are referred.</param>
		
		/// <param name="installmentNo">Progressive installment number.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdPymtSchedTbResult<TResult>(Int32 saleOrdId,Int16 installmentNo,
		                                                          Expression<Func<MA_SaleOrdPymtSched, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId,installmentNo).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdPymtSched based on primary key parameters default of MA_SaleOrdPymtSched if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdPymtSched with selector parameter</remarks>
		
		/// <param name="saleOrdId">It identifies univocally the sale order to which installments are referred.</param>
		
		/// <param name="installmentNo">Progressive installment number.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdPymtSched or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdPymtSched with selector parameter")]
        public MA_SaleOrdPymtSched GetSaleOrdPymtSched(Int32 saleOrdId,Int16 installmentNo,
												   MA_SaleOrdPymtSched @default = default)
			=> Result(Query(saleOrdId,installmentNo), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdPymtSched based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It identifies univocally the sale order to which installments are referred.</param>
		
		/// <param name="installmentNo">Progressive installment number.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdPymtSchedAsync<TResult>(Int32 saleOrdId,Int16 installmentNo,
		                                       Expression<Func<MA_SaleOrdPymtSched, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId,installmentNo).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdPymtSched based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It identifies univocally the sale order to which installments are referred.</param>
		
		/// <param name="installmentNo">Progressive installment number.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdPymtSchedTbResultAsync<TResult>(Int32 saleOrdId,Int16 installmentNo,
		                                                          Expression<Func<MA_SaleOrdPymtSched, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId,installmentNo).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdPymtSched based on primary key parameters default of MA_SaleOrdPymtSched if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdPymtSched with selector parameter</remarks>
		
		/// <param name="saleOrdId">It identifies univocally the sale order to which installments are referred.</param>
		
		/// <param name="installmentNo">Progressive installment number.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdPymtSched or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdPymtSched with selector parameter")]
        public Task<MA_SaleOrdPymtSched> GetSaleOrdPymtSchedAsync(Int32 saleOrdId,Int16 installmentNo,
												   MA_SaleOrdPymtSched @default = default)
			=> ResultAsync(Query(saleOrdId,installmentNo), @default);

		#endregion 
		
    }

}