	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	
	public partial class MA_SaleOrdDetailsAccDefObj  : BaseEntity
	{
		public MA_SaleOrdDetailsAccDefObj()
		{
		}

		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(1)]

		public Int16 Line { get =>  f_Line.TypedDBValue;  set { f_Line.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_Line { get ; private set; } = new DataInt();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? SubId { get =>  f_SubId.TypedDBValue;  set { f_SubId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SubId { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? SubIdParent { get =>  f_SubIdParent.TypedDBValue;  set { f_SubIdParent.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SubIdParent { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: new System.DateTime(1799, 12, 31, 0, 0, 0)
		/// </summary>

		public DateTime? AccDefStartDate { get =>  f_AccDefStartDate.TypedDBValue;  set { f_AccDefStartDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDate f_AccDefStartDate { get ; private set; } = new DataDate();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: new System.DateTime(1799, 12, 31, 0, 0, 0)
		/// </summary>

		public DateTime? AccDefEndDate { get =>  f_AccDefEndDate.TypedDBValue;  set { f_AccDefEndDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDate f_AccDefEndDate { get ; private set; } = new DataDate();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? UseBusinessYear { get =>  f_UseBusinessYear.TypedDBValue;  set { f_UseBusinessYear.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_UseBusinessYear { get ; private set; } = new DataBool();




	}	

	[Table("MA_SaleOrdDetailsAccDef")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdDetailsAccDefConfiguration))]
	public partial class MA_SaleOrdDetailsAccDef : MA_SaleOrdDetailsAccDefObj
	{
		public MA_SaleOrdDetailsAccDef()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdDetailsAccDefConfiguration : MA_SaleOrdDetailsAccDefConfiguration<MA_SaleOrdDetailsAccDef>
	{
		public MA_SaleOrdDetailsAccDefConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdDetailsAccDef> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdDetailsAccDefConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdDetailsAccDefObj
    {
        public MA_SaleOrdDetailsAccDefConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => new { e.SaleOrdId,e.Line }).HasName("PK_SaleOrdDetailsAccDef").IsClustered(false);
		#else
			entity.HasKey(e => new { e.SaleOrdId,e.Line }).HasName("PK_SaleOrdDetailsAccDef").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Line).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SubId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.SubIdParent).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.AccDefStartDate).HasColumnType("datetime").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.AccDefEndDate).HasColumnType("datetime").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.UseBusinessYear).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Line).HasColumnType("smallint").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SubId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.SubIdParent).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.AccDefStartDate).HasColumnType("timestamp without time zone").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.AccDefEndDate).HasColumnType("timestamp without time zone").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.UseBusinessYear).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdDetailsAccDef
	/// </summary>
	public class SaleOrdDetailsAccDefAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdDetailsAccDef>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdDetailsAccDefAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdDetailsAccDef> Query(Int32 saleOrdId,Int16 line)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId && x.Line == line);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdDetailsAccDef based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdDetailsAccDef<TResult>(Int32 saleOrdId,Int16 line,
		                                       Expression<Func<MA_SaleOrdDetailsAccDef, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdDetailsAccDef based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdDetailsAccDefTbResult<TResult>(Int32 saleOrdId,Int16 line,
		                                                          Expression<Func<MA_SaleOrdDetailsAccDef, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdDetailsAccDef based on primary key parameters default of MA_SaleOrdDetailsAccDef if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdDetailsAccDef with selector parameter</remarks>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="line"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdDetailsAccDef or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdDetailsAccDef with selector parameter")]
        public MA_SaleOrdDetailsAccDef GetSaleOrdDetailsAccDef(Int32 saleOrdId,Int16 line,
												   MA_SaleOrdDetailsAccDef @default = default)
			=> Result(Query(saleOrdId,line), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdDetailsAccDef based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdDetailsAccDefAsync<TResult>(Int32 saleOrdId,Int16 line,
		                                       Expression<Func<MA_SaleOrdDetailsAccDef, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdDetailsAccDef based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="line"></param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdDetailsAccDefTbResultAsync<TResult>(Int32 saleOrdId,Int16 line,
		                                                          Expression<Func<MA_SaleOrdDetailsAccDef, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdDetailsAccDef based on primary key parameters default of MA_SaleOrdDetailsAccDef if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdDetailsAccDef with selector parameter</remarks>
		
		/// <param name="saleOrdId"></param>
		
		/// <param name="line"></param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdDetailsAccDef or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdDetailsAccDef with selector parameter")]
        public Task<MA_SaleOrdDetailsAccDef> GetSaleOrdDetailsAccDefAsync(Int32 saleOrdId,Int16 line,
												   MA_SaleOrdDetailsAccDef @default = default)
			=> ResultAsync(Query(saleOrdId,line), @default);

		#endregion 
		
    }

}