	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	[TbCompanyIdColumn("TBCompanyID")]
	[TbRowSecurityAccessType("public_access")]	
	/// <summary>
	/// The table contains Sale order notes. It is a buffered of the table MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdNotesObj  : BaseEntity
	{
		public MA_SaleOrdNotesObj()
		{
		}

		/// <summary>
		/// Descriptive text.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Notes { get =>  f_Notes.TypedDBValue;  set { f_Notes.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Notes { get ; private set; } = new DataStr();



		/// <summary>
		/// It links the order note to the document head.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// Field used by CGM
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? TBCompanyID { get =>  f_TBCompanyID.TypedDBValue;  set { f_TBCompanyID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_TBCompanyID { get ; private set; } = new DataLng();




	}	

	[Table("MA_SaleOrdNotes")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdNotesConfiguration))]
	public partial class MA_SaleOrdNotes : MA_SaleOrdNotesObj
	{
		public MA_SaleOrdNotes()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdNotesConfiguration : MA_SaleOrdNotesConfiguration<MA_SaleOrdNotes>
	{
		public MA_SaleOrdNotesConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdNotes> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdNotesConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdNotesObj
    {
        public MA_SaleOrdNotesConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => e.SaleOrdId).HasName("PK_SaleOrdNotes").IsClustered(false);
		#else
			entity.HasKey(e => e.SaleOrdId).HasName("PK_SaleOrdNotes").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.Notes).HasMaxLength(251).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.TBCompanyID).HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.Notes).HasMaxLength(251).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.TBCompanyID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdNotes
	/// </summary>
	public class SaleOrdNotesAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdNotes>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdNotesAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdNotes> Query(Int32 saleOrdId)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdNotes based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order note to the document head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdNotes<TResult>(Int32 saleOrdId,
		                                       Expression<Func<MA_SaleOrdNotes, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdNotes based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order note to the document head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdNotesTbResult<TResult>(Int32 saleOrdId,
		                                                          Expression<Func<MA_SaleOrdNotes, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdNotes based on primary key parameters default of MA_SaleOrdNotes if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdNotes with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links the order note to the document head.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdNotes or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdNotes with selector parameter")]
        public MA_SaleOrdNotes GetSaleOrdNotes(Int32 saleOrdId,
												   MA_SaleOrdNotes @default = default)
			=> Result(Query(saleOrdId), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdNotes based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order note to the document head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdNotesAsync<TResult>(Int32 saleOrdId,
		                                       Expression<Func<MA_SaleOrdNotes, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdNotes based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order note to the document head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdNotesTbResultAsync<TResult>(Int32 saleOrdId,
		                                                          Expression<Func<MA_SaleOrdNotes, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdNotes based on primary key parameters default of MA_SaleOrdNotes if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdNotes with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links the order note to the document head.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdNotes or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdNotes with selector parameter")]
        public Task<MA_SaleOrdNotes> GetSaleOrdNotesAsync(Int32 saleOrdId,
												   MA_SaleOrdNotes @default = default)
			=> ResultAsync(Query(saleOrdId), @default);

		#endregion 
		
    }

}