	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	[TbCompanyIdColumn("TBCompanyID")]
	[TbRowSecurityAccessType("public_access")]	
	/// <summary>
	/// This table is used if the BOM components reservation is enabled. It is automatically filled in automatically retrieving the components of the BOM items present in the sale order details (MA_SaleOrdDetails). It is a slave buffered of the table MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdComponentsObj  : BaseEntity
	{
		public MA_SaleOrdComponentsObj()
		{
		}

		/// <summary>
		/// It links the order component lines to the document head.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// It links the component lines to the BOM item line present in the order.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(1)]

		public Int32 SaleOrdSubId { get =>  f_SaleOrdSubId.TypedDBValue;  set { f_SaleOrdSubId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdSubId { get ; private set; } = new DataLng();



		/// <summary>
		/// It identifies progressively the component lines relevant to a BOM item.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(2)]

		public Int16 Line { get =>  f_Line.TypedDBValue;  set { f_Line.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_Line { get ; private set; } = new DataInt();



		/// <summary>
		/// Component item code.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Component { get =>  f_Component.TypedDBValue;  set { f_Component.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Component { get ; private set; } = new DataStr();



		/// <summary>
		/// Component quantity necessary for the production of a BOM item.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? NeededQty { get =>  f_NeededQty.TypedDBValue;  set { f_NeededQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_NeededQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Unit of measure in which the component quantity is expressed.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? UoM { get =>  f_UoM.TypedDBValue;  set { f_UoM.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_UoM { get ; private set; } = new DataStr();



		/// <summary>
		/// Unit of value of the component automatically proposed according to the BOM parameters.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? UnitValue { get =>  f_UnitValue.TypedDBValue;  set { f_UnitValue.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_UnitValue { get ; private set; } = new DataMon();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: new System.DateTime(1799, 12, 31, 0, 0, 0)
		/// </summary>

		public DateTime? ExpectedDeliveryDate { get =>  f_ExpectedDeliveryDate.TypedDBValue;  set { f_ExpectedDeliveryDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDate f_ExpectedDeliveryDate { get ; private set; } = new DataDate();



		/// <summary>
		/// Waste quantity relevant to the component as reported in the BOM master.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? NeededQtyWaste { get =>  f_NeededQtyWaste.TypedDBValue;  set { f_NeededQtyWaste.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_NeededQtyWaste { get ; private set; } = new DataQty();



		/// <summary>
		/// Unit of measure in which the waste quantity is expressed.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? WasteUoM { get =>  f_WasteUoM.TypedDBValue;  set { f_WasteUoM.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_WasteUoM { get ; private set; } = new DataStr();



		/// <summary>
		/// Component description. It is automatically proposed according to the item master of the component itself.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Description { get =>  f_Description.TypedDBValue;  set { f_Description.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Description { get ; private set; } = new DataStr();



		/// <summary>
		/// Eventually item code relevant to the waste as reported in the BOM master.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Waste { get =>  f_Waste.TypedDBValue;  set { f_Waste.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Waste { get ; private set; } = new DataStr();



		/// <summary>
		/// Unit value of the waste automatically proposed according to the BOM parameters.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? WasteUnitValue { get =>  f_WasteUnitValue.TypedDBValue;  set { f_WasteUnitValue.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_WasteUnitValue { get ; private set; } = new DataMon();



		/// <summary>
		/// Component with fixed qty
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? FixedQty { get =>  f_FixedQty.TypedDBValue;  set { f_FixedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_FixedQty { get ; private set; } = new DataBool();



		/// <summary>
		/// Field used by CGM
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? TBCompanyID { get =>  f_TBCompanyID.TypedDBValue;  set { f_TBCompanyID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_TBCompanyID { get ; private set; } = new DataLng();




	}	

	[Table("MA_SaleOrdComponents")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdComponentsConfiguration))]
	public partial class MA_SaleOrdComponents : MA_SaleOrdComponentsObj
	{
		public MA_SaleOrdComponents()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdComponentsConfiguration : MA_SaleOrdComponentsConfiguration<MA_SaleOrdComponents>
	{
		public MA_SaleOrdComponentsConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdComponents> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdComponentsConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdComponentsObj
    {
        public MA_SaleOrdComponentsConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => new { e.SaleOrdId,e.SaleOrdSubId,e.Line }).HasName("PK_SaleOrdComponents").IsClustered(false);
		#else
			entity.HasKey(e => new { e.SaleOrdId,e.SaleOrdSubId,e.Line }).HasName("PK_SaleOrdComponents").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SaleOrdSubId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Line).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Component).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NeededQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.UnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ExpectedDeliveryDate).HasColumnType("datetime").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.NeededQtyWaste).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.WasteUoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Description).HasMaxLength(128).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Waste).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.WasteUnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.FixedQty).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.TBCompanyID).HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.SaleOrdSubId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Line).HasColumnType("smallint").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Component).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NeededQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.UnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ExpectedDeliveryDate).HasColumnType("timestamp without time zone").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.NeededQtyWaste).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.WasteUoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Description).HasMaxLength(128).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Waste).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.WasteUnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.FixedQty).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.TBCompanyID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdComponents
	/// </summary>
	public class SaleOrdComponentsAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdComponents>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdComponentsAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdComponents> Query(Int32 saleOrdId,Int32 saleOrdSubId,Int16 line)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId && x.SaleOrdSubId == saleOrdSubId && x.Line == line);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdComponents based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order component lines to the document head.</param>
		
		/// <param name="saleOrdSubId">It links the component lines to the BOM item line present in the order.</param>
		
		/// <param name="line">It identifies progressively the component lines relevant to a BOM item.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdComponents<TResult>(Int32 saleOrdId,Int32 saleOrdSubId,Int16 line,
		                                       Expression<Func<MA_SaleOrdComponents, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId,saleOrdSubId,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdComponents based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order component lines to the document head.</param>
		
		/// <param name="saleOrdSubId">It links the component lines to the BOM item line present in the order.</param>
		
		/// <param name="line">It identifies progressively the component lines relevant to a BOM item.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdComponentsTbResult<TResult>(Int32 saleOrdId,Int32 saleOrdSubId,Int16 line,
		                                                          Expression<Func<MA_SaleOrdComponents, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId,saleOrdSubId,line).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdComponents based on primary key parameters default of MA_SaleOrdComponents if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdComponents with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links the order component lines to the document head.</param>
		
		/// <param name="saleOrdSubId">It links the component lines to the BOM item line present in the order.</param>
		
		/// <param name="line">It identifies progressively the component lines relevant to a BOM item.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdComponents or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdComponents with selector parameter")]
        public MA_SaleOrdComponents GetSaleOrdComponents(Int32 saleOrdId,Int32 saleOrdSubId,Int16 line,
												   MA_SaleOrdComponents @default = default)
			=> Result(Query(saleOrdId,saleOrdSubId,line), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdComponents based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order component lines to the document head.</param>
		
		/// <param name="saleOrdSubId">It links the component lines to the BOM item line present in the order.</param>
		
		/// <param name="line">It identifies progressively the component lines relevant to a BOM item.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdComponentsAsync<TResult>(Int32 saleOrdId,Int32 saleOrdSubId,Int16 line,
		                                       Expression<Func<MA_SaleOrdComponents, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId,saleOrdSubId,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdComponents based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order component lines to the document head.</param>
		
		/// <param name="saleOrdSubId">It links the component lines to the BOM item line present in the order.</param>
		
		/// <param name="line">It identifies progressively the component lines relevant to a BOM item.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdComponentsTbResultAsync<TResult>(Int32 saleOrdId,Int32 saleOrdSubId,Int16 line,
		                                                          Expression<Func<MA_SaleOrdComponents, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId,saleOrdSubId,line).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdComponents based on primary key parameters default of MA_SaleOrdComponents if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdComponents with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links the order component lines to the document head.</param>
		
		/// <param name="saleOrdSubId">It links the component lines to the BOM item line present in the order.</param>
		
		/// <param name="line">It identifies progressively the component lines relevant to a BOM item.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdComponents or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdComponents with selector parameter")]
        public Task<MA_SaleOrdComponents> GetSaleOrdComponentsAsync(Int32 saleOrdId,Int32 saleOrdSubId,Int16 line,
												   MA_SaleOrdComponents @default = default)
			=> ResultAsync(Query(saleOrdId,saleOrdSubId,line), @default);

		#endregion 
		
    }

}