	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	[TbCompanyIdColumn("TBCompanyID")]
	[TbRowSecurityAccessType("public_access")]	
	/// <summary>
	/// The table contains information present in the Total tab and in the Charges tab of Sale Orders. Some fields are automatically calculated as totals of document data. These values cannot be modified by the user.
///Other data must be manually entered by the user when filling in the document and can be modified.
///It is a buffered table of the MA_SaleOrd.
	/// </summary>
	public partial class MA_SaleOrdSummaryObj  : BaseEntity
	{
		public MA_SaleOrdSummaryObj()
		{
		}

		/// <summary>
		/// Taxable amount. It is proposed as the sum of the taxable amounts present in the tax summary (field TaxableAmount of the table MA_SaleOrdTaxSummary). Always in the basic currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TaxableAmount { get =>  f_TaxableAmount.TypedDBValue;  set { f_TaxableAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TaxableAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// Tax amount of the document. It is proposed as the sum of the tax amounts present in the tax summary (field TaxAmount of the table MA_SaleOrdTaxSummary). Always in the basic currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TaxAmount { get =>  f_TaxAmount.TypedDBValue;  set { f_TaxAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TaxAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AdditionalTaxAmount { get =>  f_AdditionalTaxAmount.TypedDBValue;  set { f_AdditionalTaxAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_AdditionalTaxAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// Total amount of the document. It is proposed as the sum of the total amounts present in the tax summary (field TotalAmount of the table MA_SaleOrdTaxSummary). Always in the basic currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TotalAmount { get =>  f_TotalAmount.TypedDBValue;  set { f_TotalAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TotalAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// Document total in the document currency. If the document is in the basic currency this field is at 0.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TotalAmountDocCurr { get =>  f_TotalAmountDocCurr.TypedDBValue;  set { f_TotalAmountDocCurr.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TotalAmountDocCurr { get ; private set; } = new DataMon();



		/// <summary>
		/// Goods amount. It is the total of the lines of type Goods, net of discounts and tax. It is in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? GoodsAmount { get =>  f_GoodsAmount.TypedDBValue;  set { f_GoodsAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_GoodsAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// Goods amounts with tax in the base currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? GoodsAmountWithTax { get =>  f_GoodsAmountWithTax.TypedDBValue;  set { f_GoodsAmountWithTax.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_GoodsAmountWithTax { get ; private set; } = new DataMon();



		/// <summary>
		/// Services amount. It is the total of the lines of type Services, net of discounts and tax. It is in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? ServiceAmounts { get =>  f_ServiceAmounts.TypedDBValue;  set { f_ServiceAmounts.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_ServiceAmounts { get ; private set; } = new DataMon();



		/// <summary>
		/// Services amounts with tax in the base currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? ServiceAmountsWithTax { get =>  f_ServiceAmountsWithTax.TypedDBValue;  set { f_ServiceAmountsWithTax.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_ServiceAmountsWithTax { get ; private set; } = new DataMon();



		/// <summary>
		/// Total discount on goods. It is the total of discounts done on the lines of type Goods. It is in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DiscountOnGoods { get =>  f_DiscountOnGoods.TypedDBValue;  set { f_DiscountOnGoods.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DiscountOnGoods { get ; private set; } = new DataMon();



		/// <summary>
		/// Total discount on services. It is the total of discounts done on the lines of type Services. It is in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DiscountOnServices { get =>  f_DiscountOnServices.TypedDBValue;  set { f_DiscountOnServices.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DiscountOnServices { get ; private set; } = new DataMon();



		/// <summary>
		/// Total to be paid. It is what effectively the customer has to pay in the document currency. It is calculated as difference between the document total and free samples and allowances.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PayableAmount { get =>  f_PayableAmount.TypedDBValue;  set { f_PayableAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_PayableAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// Free samples total in the basic currency. It represents the sum of the taxable amounts of lines with Sale Type Taxable free samples or Total free samples.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? FreeSamples { get =>  f_FreeSamples.TypedDBValue;  set { f_FreeSamples.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_FreeSamples { get ; private set; } = new DataMon();



		/// <summary>
		/// Total to be paid in the basic currency. It is filled in only for documents not in the basic currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PayableAmountInBaseCurr { get =>  f_PayableAmountInBaseCurr.TypedDBValue;  set { f_PayableAmountInBaseCurr.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_PayableAmountInBaseCurr { get ; private set; } = new DataMon();



		/// <summary>
		/// First discount percentage in the field DiscountFormula.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Discount1 { get =>  f_Discount1.TypedDBValue;  set { f_Discount1.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_Discount1 { get ; private set; } = new DataPerc();



		/// <summary>
		/// Second percentage of discount in the field DiscountFormula. If the discount formula is composed by more than two percentages in cascade, here we find the percentage equivalent to the elements from the second on of the formula itself.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Discount2 { get =>  f_Discount2.TypedDBValue;  set { f_Discount2.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_Discount2 { get ; private set; } = new DataPerc();



		/// <summary>
		/// Further discount in the document. It can be proposed according to the payment term of the document or manually entered. It can be a single percentage or a discount in cascade.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? DiscountFormula { get =>  f_DiscountFormula.TypedDBValue;  set { f_DiscountFormula.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_DiscountFormula { get ; private set; } = new DataStr();



		/// <summary>
		/// Further discount amount automatically calculated according to the discount formula or manually entered.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Discounts { get =>  f_Discounts.TypedDBValue;  set { f_Discounts.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_Discounts { get ; private set; } = new DataMon();



		/// <summary>
		/// Allowance amount in the document currency. It is used to calculate the total to be paid.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Allowances { get =>  f_Allowances.TypedDBValue;  set { f_Allowances.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_Allowances { get ; private set; } = new DataMon();



		/// <summary>
		/// Advance amount (present in the Charges tab). It is in the document currency, If Collected concurrently is set (field PostAdvancesToAcc) it is subctracted by the total to be paid and posted in accounting by the invoice deriving from the document.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Advance { get =>  f_Advance.TypedDBValue;  set { f_Advance.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_Advance { get ; private set; } = new DataMon();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? ReturnedMaterial { get =>  f_ReturnedMaterial.TypedDBValue;  set { f_ReturnedMaterial.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_ReturnedMaterial { get ; private set; } = new DataMon();



		/// <summary>
		/// Packing charges for the goods in document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PackagingCharges { get =>  f_PackagingCharges.TypedDBValue;  set { f_PackagingCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_PackagingCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// It indicates if packing charges have been manually entered or automatically proposed.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PackagingChargesIsAuto { get =>  f_PackagingChargesIsAuto.TypedDBValue;  set { f_PackagingChargesIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PackagingChargesIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// Shipping charges for the goods in document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? ShippingCharges { get =>  f_ShippingCharges.TypedDBValue;  set { f_ShippingCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_ShippingCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// It indicates if shipping charges have been manually entered or automatically proposed.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? ShippingChargesIsAuto { get =>  f_ShippingChargesIsAuto.TypedDBValue;  set { f_ShippingChargesIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_ShippingChargesIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// Stamp charges. They can be automatically proposed for tax exemption customer according to the document amount or of the payment term settings. They are in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? StampsCharges { get =>  f_StampsCharges.TypedDBValue;  set { f_StampsCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_StampsCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// It indicates if stamp charges have been manually entered or automatically proposed.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? StampsChargesIsAuto { get =>  f_StampsChargesIsAuto.TypedDBValue;  set { f_StampsChargesIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_StampsChargesIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// Collection charges. They can be proposed according to the payment term and the customer master settings. They are in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? CollectionCharges { get =>  f_CollectionCharges.TypedDBValue;  set { f_CollectionCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_CollectionCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// It indicates if collection charges have been manually entered or automatically proposed.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? CollectionChargesIsAuto { get =>  f_CollectionChargesIsAuto.TypedDBValue;  set { f_CollectionChargesIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_CollectionChargesIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// Additional charges. They are automatically proposed if set in the Item Customer master and provided in the Sale parameters. They are in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AdditionalCharges { get =>  f_AdditionalCharges.TypedDBValue;  set { f_AdditionalCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_AdditionalCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// It indicates if Additional chearges have been manually entered or automatically proposed.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? AdditionalChargesIsAuto { get =>  f_AdditionalChargesIsAuto.TypedDBValue;  set { f_AdditionalChargesIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_AdditionalChargesIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// Cash on delivery percentage. Entering a percentage Mago.Net automatically sets the amount.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? CashOnDeliveryPercentage { get =>  f_CashOnDeliveryPercentage.TypedDBValue;  set { f_CashOnDeliveryPercentage.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_CashOnDeliveryPercentage { get ; private set; } = new DataPerc();



		/// <summary>
		/// Cash on delivery amount. It is a pure descriptive field that does not affect document totals. It is calculated according to the percentage set on the total to be paid. It is in the document currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? CashOnDeliveryCharges { get =>  f_CashOnDeliveryCharges.TypedDBValue;  set { f_CashOnDeliveryCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_CashOnDeliveryCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// It indicates if the advance must be post in accounting and subtracted from the total to be paid.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PostAdvancesToAcc { get =>  f_PostAdvancesToAcc.TypedDBValue;  set { f_PostAdvancesToAcc.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PostAdvancesToAcc { get ; private set; } = new DataBool();



		/// <summary>
		/// Taxable amount in the document currency. It is calculated converting the taxable amount in the basic currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TaxableAmountDocCurr { get =>  f_TaxableAmountDocCurr.TypedDBValue;  set { f_TaxableAmountDocCurr.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TaxableAmountDocCurr { get ; private set; } = new DataMon();



		/// <summary>
		/// Tax amount in the document currency. It is calculated converting the taxable amount in the basic currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TaxAmountDocCurr { get =>  f_TaxAmountDocCurr.TypedDBValue;  set { f_TaxAmountDocCurr.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TaxAmountDocCurr { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AdditionalTaxAmountDocCurr { get =>  f_AdditionalTaxAmountDocCurr.TypedDBValue;  set { f_AdditionalTaxAmountDocCurr.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_AdditionalTaxAmountDocCurr { get ; private set; } = new DataMon();



		/// <summary>
		/// Tax code stamp charges. It is automatically proposed according to the parameters.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? StampsChargesTaxCode { get =>  f_StampsChargesTaxCode.TypedDBValue;  set { f_StampsChargesTaxCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_StampsChargesTaxCode { get ; private set; } = new DataStr();



		/// <summary>
		/// Tax code collection charges. It is automatically proposed according to the parameters.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? CollectionChargesTaxCode { get =>  f_CollectionChargesTaxCode.TypedDBValue;  set { f_CollectionChargesTaxCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_CollectionChargesTaxCode { get ; private set; } = new DataStr();



		/// <summary>
		/// Unique identifier of the table. Link the table to the order head.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// Tax code shipping charges. It is editable only if it is present the first career on the document (field Carrier1 of the table MA_SaleOrdShipping), In absence of the first career this field is empty and shipping charges are subjected to the same tax code of the goods (eventually dividing it).
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ShippingChargesTaxCode { get =>  f_ShippingChargesTaxCode.TypedDBValue;  set { f_ShippingChargesTaxCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ShippingChargesTaxCode { get ; private set; } = new DataStr();



		/// <summary>
		/// Free samples total in the document currency. Valuated only for documents not in the basic currency.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? FreeSamplesDocCurr { get =>  f_FreeSamplesDocCurr.TypedDBValue;  set { f_FreeSamplesDocCurr.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_FreeSamplesDocCurr { get ; private set; } = new DataMon();



		/// <summary>
		/// It indicates if the discount amount has been manually entered or calculated according to the discount formula.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? DiscountsIsAuto { get =>  f_DiscountsIsAuto.TypedDBValue;  set { f_DiscountsIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_DiscountsIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? InsuranceCharges { get =>  f_InsuranceCharges.TypedDBValue;  set { f_InsuranceCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_InsuranceCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? InsuranceChargesIsAuto { get =>  f_InsuranceChargesIsAuto.TypedDBValue;  set { f_InsuranceChargesIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_InsuranceChargesIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PaymentDiscount1Perc { get =>  f_PaymentDiscount1Perc.TypedDBValue;  set { f_PaymentDiscount1Perc.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_PaymentDiscount1Perc { get ; private set; } = new DataPerc();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PaymentDiscount1PercAuto { get =>  f_PaymentDiscount1PercAuto.TypedDBValue;  set { f_PaymentDiscount1PercAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PaymentDiscount1PercAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? PaymentDiscount1Days { get =>  f_PaymentDiscount1Days.TypedDBValue;  set { f_PaymentDiscount1Days.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_PaymentDiscount1Days { get ; private set; } = new DataInt();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PaymentDiscount1DaysAuto { get =>  f_PaymentDiscount1DaysAuto.TypedDBValue;  set { f_PaymentDiscount1DaysAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PaymentDiscount1DaysAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PaymentDiscount1Amount { get =>  f_PaymentDiscount1Amount.TypedDBValue;  set { f_PaymentDiscount1Amount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_PaymentDiscount1Amount { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PaymentDiscount1AmountAuto { get =>  f_PaymentDiscount1AmountAuto.TypedDBValue;  set { f_PaymentDiscount1AmountAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PaymentDiscount1AmountAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PaymentDiscount2Perc { get =>  f_PaymentDiscount2Perc.TypedDBValue;  set { f_PaymentDiscount2Perc.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_PaymentDiscount2Perc { get ; private set; } = new DataPerc();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PaymentDiscount2PercAuto { get =>  f_PaymentDiscount2PercAuto.TypedDBValue;  set { f_PaymentDiscount2PercAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PaymentDiscount2PercAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? PaymentDiscount2Days { get =>  f_PaymentDiscount2Days.TypedDBValue;  set { f_PaymentDiscount2Days.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_PaymentDiscount2Days { get ; private set; } = new DataInt();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PaymentDiscount2DaysAuto { get =>  f_PaymentDiscount2DaysAuto.TypedDBValue;  set { f_PaymentDiscount2DaysAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PaymentDiscount2DaysAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PaymentDiscount2Amount { get =>  f_PaymentDiscount2Amount.TypedDBValue;  set { f_PaymentDiscount2Amount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_PaymentDiscount2Amount { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PaymentDiscount2AmountAuto { get =>  f_PaymentDiscount2AmountAuto.TypedDBValue;  set { f_PaymentDiscount2AmountAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PaymentDiscount2AmountAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// Total for Payments discount.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PaymentDiscountTotal { get =>  f_PaymentDiscountTotal.TypedDBValue;  set { f_PaymentDiscountTotal.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_PaymentDiscountTotal { get ; private set; } = new DataMon();



		/// <summary>
		/// The sum of Goods/Services and Charges not subjected to &quot;Skonto&quot;. The field is hidden.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PaymentDiscountTotalToExclude { get =>  f_PaymentDiscountTotalToExclude.TypedDBValue;  set { f_PaymentDiscountTotalToExclude.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_PaymentDiscountTotalToExclude { get ; private set; } = new DataMon();



		/// <summary>
		/// If true, the shipping charges are not included in the Total for Payment Discount.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoPayDiscOnShipping { get =>  f_NoPayDiscOnShipping.TypedDBValue;  set { f_NoPayDiscOnShipping.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoPayDiscOnShipping { get ; private set; } = new DataBool();



		/// <summary>
		/// If true, the packing charges are not included in the Total for Payment Discount.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoPayDiscOnPacking { get =>  f_NoPayDiscOnPacking.TypedDBValue;  set { f_NoPayDiscOnPacking.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoPayDiscOnPacking { get ; private set; } = new DataBool();



		/// <summary>
		/// If true, the collection charges are not included in the Total for Payment Discount.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoPayDiscOnCollection { get =>  f_NoPayDiscOnCollection.TypedDBValue;  set { f_NoPayDiscOnCollection.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoPayDiscOnCollection { get ; private set; } = new DataBool();



		/// <summary>
		/// If true, the additional charges are not included in the Total for Payment Discount.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoPayDiscOnAdditional { get =>  f_NoPayDiscOnAdditional.TypedDBValue;  set { f_NoPayDiscOnAdditional.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoPayDiscOnAdditional { get ; private set; } = new DataBool();



		/// <summary>
		/// Field used by CGM
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? TBCompanyID { get =>  f_TBCompanyID.TypedDBValue;  set { f_TBCompanyID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_TBCompanyID { get ; private set; } = new DataLng();




	}	

	[Table("MA_SaleOrdSummary")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdSummaryConfiguration))]
	public partial class MA_SaleOrdSummary : MA_SaleOrdSummaryObj
	{
		public MA_SaleOrdSummary()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdSummaryConfiguration : MA_SaleOrdSummaryConfiguration<MA_SaleOrdSummary>
	{
		public MA_SaleOrdSummaryConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdSummary> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdSummaryConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdSummaryObj
    {
        public MA_SaleOrdSummaryConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => e.SaleOrdId).HasName("PK_SaleOrdSummary").IsClustered(false);
		#else
			entity.HasKey(e => e.SaleOrdId).HasName("PK_SaleOrdSummary").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.TaxableAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalTaxAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TotalAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TotalAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GoodsAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GoodsAmountWithTax).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ServiceAmounts).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ServiceAmountsWithTax).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountOnGoods).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountOnServices).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PayableAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.FreeSamples).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PayableAmountInBaseCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount1).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount2).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountFormula).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Discounts).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Allowances).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Advance).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ReturnedMaterial).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PackagingCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PackagingChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.ShippingCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ShippingChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.StampsCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.StampsChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.CollectionCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.CollectionChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.AdditionalCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.CashOnDeliveryPercentage).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.CashOnDeliveryCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PostAdvancesToAcc).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.TaxableAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalTaxAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.StampsChargesTaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CollectionChargesTaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.ShippingChargesTaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.FreeSamplesDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountsIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.InsuranceCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.InsuranceChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PaymentDiscount1Perc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount1PercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PaymentDiscount1Days).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PaymentDiscount1DaysAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PaymentDiscount1Amount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount1AmountAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PaymentDiscount2Perc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount2PercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PaymentDiscount2Days).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PaymentDiscount2DaysAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PaymentDiscount2Amount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount2AmountAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PaymentDiscountTotal).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscountTotalToExclude).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NoPayDiscOnShipping).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.NoPayDiscOnPacking).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.NoPayDiscOnCollection).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.NoPayDiscOnAdditional).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.TBCompanyID).HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.TaxableAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalTaxAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TotalAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TotalAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GoodsAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GoodsAmountWithTax).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ServiceAmounts).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ServiceAmountsWithTax).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountOnGoods).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountOnServices).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PayableAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.FreeSamples).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PayableAmountInBaseCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount1).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount2).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountFormula).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Discounts).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Allowances).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Advance).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ReturnedMaterial).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PackagingCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PackagingChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.ShippingCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ShippingChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.StampsCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.StampsChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.CollectionCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.CollectionChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.AdditionalCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.CashOnDeliveryPercentage).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.CashOnDeliveryCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PostAdvancesToAcc).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.TaxableAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalTaxAmountDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.StampsChargesTaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CollectionChargesTaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.ShippingChargesTaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.FreeSamplesDocCurr).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountsIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.InsuranceCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.InsuranceChargesIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PaymentDiscount1Perc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount1PercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PaymentDiscount1Days).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PaymentDiscount1DaysAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PaymentDiscount1Amount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount1AmountAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PaymentDiscount2Perc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount2PercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PaymentDiscount2Days).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PaymentDiscount2DaysAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PaymentDiscount2Amount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscount2AmountAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PaymentDiscountTotal).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PaymentDiscountTotalToExclude).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NoPayDiscOnShipping).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.NoPayDiscOnPacking).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.NoPayDiscOnCollection).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.NoPayDiscOnAdditional).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.TBCompanyID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdSummary
	/// </summary>
	public class SaleOrdSummaryAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdSummary>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdSummaryAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdSummary> Query(Int32 saleOrdId)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdSummary based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">Unique identifier of the table. Link the table to the order head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdSummary<TResult>(Int32 saleOrdId,
		                                       Expression<Func<MA_SaleOrdSummary, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdSummary based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">Unique identifier of the table. Link the table to the order head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdSummaryTbResult<TResult>(Int32 saleOrdId,
		                                                          Expression<Func<MA_SaleOrdSummary, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdSummary based on primary key parameters default of MA_SaleOrdSummary if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdSummary with selector parameter</remarks>
		
		/// <param name="saleOrdId">Unique identifier of the table. Link the table to the order head.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdSummary or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdSummary with selector parameter")]
        public MA_SaleOrdSummary GetSaleOrdSummary(Int32 saleOrdId,
												   MA_SaleOrdSummary @default = default)
			=> Result(Query(saleOrdId), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdSummary based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">Unique identifier of the table. Link the table to the order head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdSummaryAsync<TResult>(Int32 saleOrdId,
		                                       Expression<Func<MA_SaleOrdSummary, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdSummary based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">Unique identifier of the table. Link the table to the order head.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdSummaryTbResultAsync<TResult>(Int32 saleOrdId,
		                                                          Expression<Func<MA_SaleOrdSummary, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdSummary based on primary key parameters default of MA_SaleOrdSummary if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdSummary with selector parameter</remarks>
		
		/// <param name="saleOrdId">Unique identifier of the table. Link the table to the order head.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdSummary or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdSummary with selector parameter")]
        public Task<MA_SaleOrdSummary> GetSaleOrdSummaryAsync(Int32 saleOrdId,
												   MA_SaleOrdSummary @default = default)
			=> ResultAsync(Query(saleOrdId), @default);

		#endregion 
		
    }

}