	// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using System.Linq.Expressions;
using System.Linq;
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces;
using System.Threading.Tasks;
using Microarea.Generic.DataObj;


namespace OttieniToken.MOToken.Model
{
	[TbCompanyIdColumn("TBCompanyID")]
	[TbRowSecurityAccessType("public_access")]	
	/// <summary>
	/// This table contains the details of the customer order and it is a slave one to many of the MA_SaleOrd table.
	/// </summary>
	public partial class MA_SaleOrdDetailsObj  : BaseEntity
	{
		public MA_SaleOrdDetailsObj()
		{
		}

		/// <summary>
		/// It indicates the position in the grid of each document line. It is, together with SaleOrdId, the table key.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(1)]

		public Int16 Line { get =>  f_Line.TypedDBValue;  set { f_Line.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_Line { get ; private set; } = new DataInt();



		/// <summary>
		/// It indicates the lines of type Goods, Services and Descriptive, establishing the reference from other documents (for example delivery note).
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? Position { get =>  f_Position.TypedDBValue;  set { f_Position.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_Position { get ; private set; } = new DataInt();



		/// <summary>
		/// It establishes if the record is relevant to an inventory item (good, service or descriptive) or to a note.
		/// 	
		/// DefaultValue: 3538947
		/// </summary>

		public int? LineType { get =>  f_LineType.TypedDBValue;  set { f_LineType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_LineType { get ; private set; } = new DataEnum(3538947);



		/// <summary>
		/// It reports the item description or a note according to the Line Type. It can be retrieved from the Item Master Data.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Description { get =>  f_Description.TypedDBValue;  set { f_Description.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Description { get ; private set; } = new DataStr();



		/// <summary>
		/// It indicates that the line is not to be printed (standard reports).
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoPrint { get =>  f_NoPrint.TypedDBValue;  set { f_NoPrint.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoPrint { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates that the line must not be carried forward in delivery notes.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoDN { get =>  f_NoDN.TypedDBValue;  set { f_NoDN.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoDN { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates that the line must not be carried forward in invoice.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NoInvoice { get =>  f_NoInvoice.TypedDBValue;  set { f_NoInvoice.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NoInvoice { get ; private set; } = new DataBool();



		/// <summary>
		/// Item code. The insertion of this information causes the automatic proposition of several fields such as, for example, description, unit of measure, unit value etc. It is not editable for lines of type Note and Descriptive.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Item { get =>  f_Item.TypedDBValue;  set { f_Item.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Item { get ; private set; } = new DataStr();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Lot { get =>  f_Lot.TypedDBValue;  set { f_Lot.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Lot { get ; private set; } = new DataStr();



		/// <summary>
		/// It is the item variant.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Variant { get =>  f_Variant.TypedDBValue;  set { f_Variant.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Variant { get ; private set; } = new DataStr();



		/// <summary>
		/// Drawing relevant to Bill of Material items.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Drawing { get =>  f_Drawing.TypedDBValue;  set { f_Drawing.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Drawing { get ; private set; } = new DataStr();



		/// <summary>
		/// Customer to which the document is headed.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Customer { get =>  f_Customer.TypedDBValue;  set { f_Customer.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Customer { get ; private set; } = new DataStr();



		/// <summary>
		/// Document date.
		/// 	
		/// DefaultValue: new System.DateTime(1799, 12, 31, 0, 0, 0)
		/// </summary>

		public DateTime? OrderDate { get =>  f_OrderDate.TypedDBValue;  set { f_OrderDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDate f_OrderDate { get ; private set; } = new DataDate();



		/// <summary>
		/// Internal order number.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? InternalOrdNo { get =>  f_InternalOrdNo.TypedDBValue;  set { f_InternalOrdNo.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_InternalOrdNo { get ; private set; } = new DataStr();



		/// <summary>
		/// Department relevant to the item. It is automatically proposed according to the item master settings.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Department { get =>  f_Department.TypedDBValue;  set { f_Department.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Department { get ; private set; } = new DataStr();



		/// <summary>
		/// Unit of measure to which the quantity is referred. It is automatically proposed according to the item master settings.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? UoM { get =>  f_UoM.TypedDBValue;  set { f_UoM.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_UoM { get ; private set; } = new DataStr();



		/// <summary>
		/// Ordered quantity.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Qty { get =>  f_Qty.TypedDBValue;  set { f_Qty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_Qty { get ; private set; } = new DataQty();



		/// <summary>
		/// Additional quantity. If the unit of measure provides the coefficients management it can be used for the quantity calculation.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AdditionalQty1 { get =>  f_AdditionalQty1.TypedDBValue;  set { f_AdditionalQty1.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_AdditionalQty1 { get ; private set; } = new DataQty();



		/// <summary>
		/// Additional quantity. If the unit of measure provides the coefficients management it can be used for the quantity calculation.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AdditionalQty2 { get =>  f_AdditionalQty2.TypedDBValue;  set { f_AdditionalQty2.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_AdditionalQty2 { get ; private set; } = new DataQty();



		/// <summary>
		/// Additional quantity. If the unit of measure provides the coefficients management it can be used for the quantity calculation.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AdditionalQty3 { get =>  f_AdditionalQty3.TypedDBValue;  set { f_AdditionalQty3.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_AdditionalQty3 { get ; private set; } = new DataQty();



		/// <summary>
		/// Additional quantity. If the unit of measure provides the coefficients management it can be used for the quantity calculation.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AdditionalQty { get =>  f_AdditionalQty.TypedDBValue;  set { f_AdditionalQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_AdditionalQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Unit Value. It is automatically proposed according to the item master.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? UnitValue { get =>  f_UnitValue.TypedDBValue;  set { f_UnitValue.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_UnitValue { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? NetPrice { get =>  f_NetPrice.TypedDBValue;  set { f_NetPrice.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_NetPrice { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? NetPriceIsAuto { get =>  f_NetPriceIsAuto.TypedDBValue;  set { f_NetPriceIsAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_NetPriceIsAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// Line taxable amount. It is automatically calculated according to the base quantity, unit value and discount formula.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TaxableAmount { get =>  f_TaxableAmount.TypedDBValue;  set { f_TaxableAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TaxableAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// TAX code. It is automatically proposed according to the item and customer master.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? TaxCode { get =>  f_TaxCode.TypedDBValue;  set { f_TaxCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_TaxCode { get ; private set; } = new DataStr();



		/// <summary>
		/// Line total amount. It is automatically calculated according to the taxable amount and TAX code.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? TotalAmount { get =>  f_TotalAmount.TypedDBValue;  set { f_TotalAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_TotalAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// Discount 1 percentage (cascade discount). It is automatically calculated according to the formula discount.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Discount1 { get =>  f_Discount1.TypedDBValue;  set { f_Discount1.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_Discount1 { get ; private set; } = new DataPerc();



		/// <summary>
		/// Discount 2 percentage (cascade discount). It is automatically calculated according to the formula discount.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? Discount2 { get =>  f_Discount2.TypedDBValue;  set { f_Discount2.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_Discount2 { get ; private set; } = new DataPerc();



		/// <summary>
		/// Discount formula. It is automatically proposed according to the customer and item master.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? DiscountFormula { get =>  f_DiscountFormula.TypedDBValue;  set { f_DiscountFormula.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_DiscountFormula { get ; private set; } = new DataStr();



		/// <summary>
		/// Discount Amount. It is calculated according to the discount formula.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DiscountAmount { get =>  f_DiscountAmount.TypedDBValue;  set { f_DiscountAmount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DiscountAmount { get ; private set; } = new DataMon();



		/// <summary>
		/// Expected delivery date. It is automatically proposed according to the expected delivery date in the document head (field ExpectedDeliveryDate of the table MA_SaleOrd).
		/// 	
		/// DefaultValue: new System.DateTime(1799, 12, 31, 0, 0, 0)
		/// </summary>

		public DateTime? ExpectedDeliveryDate { get =>  f_ExpectedDeliveryDate.TypedDBValue;  set { f_ExpectedDeliveryDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDate f_ExpectedDeliveryDate { get ; private set; } = new DataDate();



		/// <summary>
		/// Confirmed delivery date. It is automatically proposed according to the confirmed delivery date in the document head (field ConfirmedDeliveryDate of the table MA_SaleOrd).
		/// 	
		/// DefaultValue: new System.DateTime(1799, 12, 31, 0, 0, 0)
		/// </summary>

		public DateTime? ConfirmedDeliveryDate { get =>  f_ConfirmedDeliveryDate.TypedDBValue;  set { f_ConfirmedDeliveryDate.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDate f_ConfirmedDeliveryDate { get ; private set; } = new DataDate();



		/// <summary>
		/// Delivered quantity. It is automatically updated fulfilling the order in a delivery document.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DeliveredQty { get =>  f_DeliveredQty.TypedDBValue;  set { f_DeliveredQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_DeliveredQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Preshipped quantity. It is automatically updated fulfilling the sale order in preshipping.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PreShippedQty { get =>  f_PreShippedQty.TypedDBValue;  set { f_PreShippedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PreShippedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Invoiced quantity. It is automatically updated fulfilling the sale order in invoice or invoicing the delivery note in which the order has been fulfilled.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? InvoicedQty { get =>  f_InvoicedQty.TypedDBValue;  set { f_InvoicedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_InvoicedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Sale type. It indicates if the item has been let for a value or not. It is automatically proposed according to the item master. It is editable only for lines of type Goods or Services.
		/// 	
		/// DefaultValue: 3670020
		/// </summary>

		public int? SaleType { get =>  f_SaleType.TypedDBValue;  set { f_SaleType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_SaleType { get ; private set; } = new DataEnum(3670020);



		/// <summary>
		/// Number of packs. It is automatically proposed according to the item master. It is editable only for lines of type Goods.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? NoOfPacks { get =>  f_NoOfPacks.TypedDBValue;  set { f_NoOfPacks.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_NoOfPacks { get ; private set; } = new DataInt();



		/// <summary>
		/// Packs unit of measure. It is automatically proposed according to the item master. It is editable only for lines of type Goods.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? PacksUoM { get =>  f_PacksUoM.TypedDBValue;  set { f_PacksUoM.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_PacksUoM { get ; private set; } = new DataStr();



		/// <summary>
		/// Gross weight. It is automatically proposed according to the item master. It is editable only for lines of type Goods.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? GrossWeight { get =>  f_GrossWeight.TypedDBValue;  set { f_GrossWeight.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDbl f_GrossWeight { get ; private set; } = new DataDbl();



		/// <summary>
		/// Net weight. It is automatically proposed according to the item master. It is editable only for lines of type Goods.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? NetWeight { get =>  f_NetWeight.TypedDBValue;  set { f_NetWeight.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataDbl f_NetWeight { get ; private set; } = new DataDbl();



		/// <summary>
		/// Gross volume. It is automatically proposed according to the item master.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? GrossVolume { get =>  f_GrossVolume.TypedDBValue;  set { f_GrossVolume.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_GrossVolume { get ; private set; } = new DataQty();



		/// <summary>
		/// It indicates that the line has been completely delivered. It is automatically set when the quantity delivered is equal to the line quantity. It can be forced when manually fulfilling the delivery document. It is editable only for lines of type Goods, Services or Descriptive.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Delivered { get =>  f_Delivered.TypedDBValue;  set { f_Delivered.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Delivered { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates that the line has been completely invoiced. It is automatically set when the quantity invoiced is equal to the line quantity. It can be forced when manually fulfilling in invoice. It is editable only for lines of type Goods, Services or Descriptive.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Invoiced { get =>  f_Invoiced.TypedDBValue;  set { f_Invoiced.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Invoiced { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates that the line has been completely invoiced.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? PreShipped { get =>  f_PreShipped.TypedDBValue;  set { f_PreShipped.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_PreShipped { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates that the line has been cancelled. It is editable only for lines of type Goods, Services or Descriptive.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Cancelled { get =>  f_Cancelled.TypedDBValue;  set { f_Cancelled.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Cancelled { get ; private set; } = new DataBool();



		/// <summary>
		/// It links the order lines with the head of the same document.
		/// This property is a primary Key 	
		/// DefaultValue: 0
		/// </summary>
		[TbPrimaryKey(0)]

		public Int32 SaleOrdId { get =>  f_SaleOrdId.TypedDBValue;  set { f_SaleOrdId.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SaleOrdId { get ; private set; } = new DataLng();



		/// <summary>
		/// It links together lines of the same product composition. It is automatically set for the lines relevant to a same product composition item.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? KitNo { get =>  f_KitNo.TypedDBValue;  set { f_KitNo.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_KitNo { get ; private set; } = new DataInt();



		/// <summary>
		/// For the lines of the product composition components it points out the necessary quantity for any product composition item. It is automatically proposed according to the product composition.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? KitQty { get =>  f_KitQty.TypedDBValue;  set { f_KitQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_KitQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Job to be used when posting in Cost Accounting. It is automatically proposed according to the job entered in the Item Master or, if it not available, in the document head (field Job of the table SaleOrd).
///This field, as well as the relevant master, is available even if the Cost Accounting module is not activated: in such case it becomes a descriptive field according to which it is possible to filter in some particular automatic procedures.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Job { get =>  f_Job.TypedDBValue;  set { f_Job.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Job { get ; private set; } = new DataStr();



		/// <summary>
		/// Cost center to be used when post in Cost Accounting. It is automatically proposed according to the cost center present in the Item master or, if not available, in the document head (field CostCenter of the table SaleOrd).
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? CostCenter { get =>  f_CostCenter.TypedDBValue;  set { f_CostCenter.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_CostCenter { get ; private set; } = new DataStr();



		/// <summary>
		/// Product line to be used when post in Cost Accounting (only Enterprise edition). It is automatically proposed according to the product line present in the Item Master or, if not available, in the document head (field ProductLine of the table SaleOrd).
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ProductLine { get =>  f_ProductLine.TypedDBValue;  set { f_ProductLine.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ProductLine { get ; private set; } = new DataStr();



		/// <summary>
		/// Commission percentage due to the salesperson. It can be automatically calculated according to the Commission Policy.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? CommPerc { get =>  f_CommPerc.TypedDBValue;  set { f_CommPerc.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_CommPerc { get ; private set; } = new DataPerc();



		/// <summary>
		/// Commission percentage due to the AreaManager. It can be automatically calculated according to the Commission Policy.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AreaManagerCommPerc { get =>  f_AreaManagerCommPerc.TypedDBValue;  set { f_AreaManagerCommPerc.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataPerc f_AreaManagerCommPerc { get ; private set; } = new DataPerc();



		/// <summary>
		/// Amount in deduction of the salesperson commission. It is automatically calculated according to the line discount if the appropriate formula has been set.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? SalespersonDiscount { get =>  f_SalespersonDiscount.TypedDBValue;  set { f_SalespersonDiscount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_SalespersonDiscount { get ; private set; } = new DataMon();



		/// <summary>
		/// Commission category on which commissions can be calculated. It is automatically proposed according to the customer master or item master basing on the commission policy used.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? CommissionCtg { get =>  f_CommissionCtg.TypedDBValue;  set { f_CommissionCtg.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_CommissionCtg { get ; private set; } = new DataStr();



		/// <summary>
		/// Link with the Production Plan.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? ProductionPlanId { get =>  f_ProductionPlanId.TypedDBValue;  set { f_ProductionPlanId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_ProductionPlanId { get ; private set; } = new DataLng();



		/// <summary>
		/// Link with the Production Plan.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ProductionPlanNo { get =>  f_ProductionPlanNo.TypedDBValue;  set { f_ProductionPlanNo.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ProductionPlanNo { get ; private set; } = new DataStr();



		/// <summary>
		/// Link with the Production Plan.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? ProductionPlanLine { get =>  f_ProductionPlanLine.TypedDBValue;  set { f_ProductionPlanLine.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_ProductionPlanLine { get ; private set; } = new DataInt();



		/// <summary>
		/// Accounting offset. It is automatically proposed according to the customer/item master &#8211; item &#8211; customer.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Offset { get =>  f_Offset.TypedDBValue;  set { f_Offset.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Offset { get ; private set; } = new DataStr();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? BookedQty { get =>  f_BookedQty.TypedDBValue;  set { f_BookedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_BookedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Salesperson commission amount calculated according to the salesperson basic amount and salesperson commission percentage.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? SalespersonComm { get =>  f_SalespersonComm.TypedDBValue;  set { f_SalespersonComm.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_SalespersonComm { get ; private set; } = new DataMon();



		/// <summary>
		/// It identifies the progressive number of lines insertion.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? SubId { get =>  f_SubId.TypedDBValue;  set { f_SubId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_SubId { get ; private set; } = new DataLng();



		/// <summary>
		/// It indicates the Bill of Materials items if the components reservation management is enabled.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? BOMItem { get =>  f_BOMItem.TypedDBValue;  set { f_BOMItem.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_BOMItem { get ; private set; } = new DataBool();



		/// <summary>
		/// Storage code of phase 1 to move (Reserved from sale orders). It is automatically proposed according to what is defined in the document head.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? StoragePhase1 { get =>  f_StoragePhase1.TypedDBValue;  set { f_StoragePhase1.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_StoragePhase1 { get ; private set; } = new DataStr();



		/// <summary>
		/// Storage code of phase 2 to move (Reserved from sale orders). It is automatically proposed according to what is defined in the document head.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? StoragePhase2 { get =>  f_StoragePhase2.TypedDBValue;  set { f_StoragePhase2.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_StoragePhase2 { get ; private set; } = new DataStr();



		/// <summary>
		/// Specificator code of the storage of phase 1 (if provided). It is automatically proposed according to what is provided in the document head.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? SpecificatorPhase1 { get =>  f_SpecificatorPhase1.TypedDBValue;  set { f_SpecificatorPhase1.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_SpecificatorPhase1 { get ; private set; } = new DataStr();



		/// <summary>
		/// Specificator code of the storage of phase 2 (if provided). It is automatically proposed according to what is provided in the document head.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? SpecificatorPhase2 { get =>  f_SpecificatorPhase2.TypedDBValue;  set { f_SpecificatorPhase2.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_SpecificatorPhase2 { get ; private set; } = new DataStr();



		/// <summary>
		/// Descriptive field. It can be used to manually enter the reference to a line number of an external document.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? ExternalLineReference { get =>  f_ExternalLineReference.TypedDBValue;  set { f_ExternalLineReference.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_ExternalLineReference { get ; private set; } = new DataInt();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? CustomerLotNo { get =>  f_CustomerLotNo.TypedDBValue;  set { f_CustomerLotNo.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_CustomerLotNo { get ; private set; } = new DataStr();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? ProductionJobId { get =>  f_ProductionJobId.TypedDBValue;  set { f_ProductionJobId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_ProductionJobId { get ; private set; } = new DataLng();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ProductionJobNo { get =>  f_ProductionJobNo.TypedDBValue;  set { f_ProductionJobNo.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ProductionJobNo { get ; private set; } = new DataStr();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? ProductionJobSubId { get =>  f_ProductionJobSubId.TypedDBValue;  set { f_ProductionJobSubId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_ProductionJobSubId { get ; private set; } = new DataLng();



		/// <summary>
		/// Pure descriptive field, not automatically managed.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? ReferenceDocId { get =>  f_ReferenceDocId.TypedDBValue;  set { f_ReferenceDocId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_ReferenceDocId { get ; private set; } = new DataLng();



		/// <summary>
		/// Descriptive field. It can be used to manually enter the reference to an external document.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ReferenceDocNo { get =>  f_ReferenceDocNo.TypedDBValue;  set { f_ReferenceDocNo.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ReferenceDocNo { get ; private set; } = new DataStr();



		/// <summary>
		/// In the case in which the line derives from the loading of a customer quotation it indicates the quotation ID.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? ReferenceQuotationId { get =>  f_ReferenceQuotationId.TypedDBValue;  set { f_ReferenceQuotationId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_ReferenceQuotationId { get ; private set; } = new DataLng();



		/// <summary>
		/// In the case in which the line derives from the loading of a customer quotation it indicates the SubId of the quotation line.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? ReferenceQuotationSubId { get =>  f_ReferenceQuotationSubId.TypedDBValue;  set { f_ReferenceQuotationSubId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_ReferenceQuotationSubId { get ; private set; } = new DataLng();



		/// <summary>
		/// Descriptive field that in the case in which the line derives from the loading of a customer quotation it indicates the number and document date in addition to the line of the same document.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ReferenceQuotation { get =>  f_ReferenceQuotation.TypedDBValue;  set { f_ReferenceQuotation.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ReferenceQuotation { get ; private set; } = new DataStr();



		/// <summary>
		/// Descriptive field in which one can enter some notes.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? Notes { get =>  f_Notes.TypedDBValue;  set { f_Notes.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_Notes { get ; private set; } = new DataStr();



		/// <summary>
		/// Basic amount on which calculate commissions due to the SalesPerson. It can be automatically calculated according to the Commission Policy settings.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? BaseSalesperson { get =>  f_BaseSalesperson.TypedDBValue;  set { f_BaseSalesperson.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_BaseSalesperson { get ; private set; } = new DataMon();



		/// <summary>
		/// Basic amount on which calculate commissions due to the AreaManager. It can be automatically calculated according to the Commission Policy settings.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? BaseAreaManager { get =>  f_BaseAreaManager.TypedDBValue;  set { f_BaseAreaManager.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_BaseAreaManager { get ; private set; } = new DataMon();



		/// <summary>
		/// Commission amount due to the AreaManager. It can be automatically calculated according to the Commission Policy settings.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AreaManagerComm { get =>  f_AreaManagerComm.TypedDBValue;  set { f_AreaManagerComm.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_AreaManagerComm { get ; private set; } = new DataMon();



		/// <summary>
		/// Commission category on which commissions can be automatically calculated. It can be automatically proposed according to the customer or item master basing on the commission policy used.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? AreaManagerCommCtg { get =>  f_AreaManagerCommCtg.TypedDBValue;  set { f_AreaManagerCommCtg.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_AreaManagerCommCtg { get ; private set; } = new DataStr();



		/// <summary>
		/// It indicates if the salesperson commission percentage is automatic or manual.
		/// 	
		/// DefaultValue: true
		/// </summary>

		public bool? CommPercAuto { get =>  f_CommPercAuto.TypedDBValue;  set { f_CommPercAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_CommPercAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the AreaManager commission percentage is automatic or manual.
		/// 	
		/// DefaultValue: true
		/// </summary>

		public bool? AreaManagerCommPercAuto { get =>  f_AreaManagerCommPercAuto.TypedDBValue;  set { f_AreaManagerCommPercAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_AreaManagerCommPercAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the salesperson commission is automatic or manual.
		/// 	
		/// DefaultValue: true
		/// </summary>

		public bool? SalespersonCommAuto { get =>  f_SalespersonCommAuto.TypedDBValue;  set { f_SalespersonCommAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_SalespersonCommAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the AreaManager commission is automatic or manual.
		/// 	
		/// DefaultValue: true
		/// </summary>

		public bool? AreaManagerCommAuto { get =>  f_AreaManagerCommAuto.TypedDBValue;  set { f_AreaManagerCommAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_AreaManagerCommAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the salesperson commission category is automatic or manual.
		/// 	
		/// DefaultValue: true
		/// </summary>

		public bool? SalespersonCommCtgAuto { get =>  f_SalespersonCommCtgAuto.TypedDBValue;  set { f_SalespersonCommCtgAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_SalespersonCommCtgAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates if the AreaManager commission category is automatic or manual.
		/// 	
		/// DefaultValue: true
		/// </summary>

		public bool? AreaManagerCommCtgAuto { get =>  f_AreaManagerCommCtgAuto.TypedDBValue;  set { f_AreaManagerCommCtgAuto.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_AreaManagerCommCtgAuto { get ; private set; } = new DataBool();



		/// <summary>
		/// It is the confirmation level relevant to Open Orders.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? ConfirmationLevel { get =>  f_ConfirmationLevel.TypedDBValue;  set { f_ConfirmationLevel.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_ConfirmationLevel { get ; private set; } = new DataStr();



		/// <summary>
		/// Customer item code (item customer master).
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? CustomerCode { get =>  f_CustomerCode.TypedDBValue;  set { f_CustomerCode.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_CustomerCode { get ; private set; } = new DataStr();



		/// <summary>
		/// Sale price list if the Price list on document management is enabled.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? PriceList { get =>  f_PriceList.TypedDBValue;  set { f_PriceList.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_PriceList { get ; private set; } = new DataStr();



		/// <summary>
		/// It indicates if the goods have been totally picked by the Picking List.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Picked { get =>  f_Picked.TypedDBValue;  set { f_Picked.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Picked { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates the quantity picked by the Picking List.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PickedQty { get =>  f_PickedQty.TypedDBValue;  set { f_PickedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PickedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// It indicates the quantity picked and delivered.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PickedAndDeliveredQty { get =>  f_PickedAndDeliveredQty.TypedDBValue;  set { f_PickedAndDeliveredQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PickedAndDeliveredQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Field for internal use.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? PreShippedAndDeliveredQty { get =>  f_PreShippedAndDeliveredQty.TypedDBValue;  set { f_PreShippedAndDeliveredQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_PreShippedAndDeliveredQty { get ; private set; } = new DataQty();



		/// <summary>
		/// It indicates if the goods have been totally allocated.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Allocated { get =>  f_Allocated.TypedDBValue;  set { f_Allocated.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Allocated { get ; private set; } = new DataBool();



		/// <summary>
		/// It indicates the allocated quantity.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? AllocatedQty { get =>  f_AllocatedQty.TypedDBValue;  set { f_AllocatedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_AllocatedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// It allows to link the note lines to any other goods or services type line. This field is enabled if the module Warehouse Management System is activated.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int16? ReferredPosition { get =>  f_ReferredPosition.TypedDBValue;  set { f_ReferredPosition.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataInt f_ReferredPosition { get ; private set; } = new DataInt();



		/// <summary>
		/// Cross Reference Type.
		/// 	
		/// DefaultValue: 27066368
		/// </summary>

		public int? CRRefType { get =>  f_CRRefType.TypedDBValue;  set { f_CRRefType.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataEnum f_CRRefType { get ; private set; } = new DataEnum(27066368);



		/// <summary>
		/// Cross Reference identifier.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? CRRefID { get =>  f_CRRefID.TypedDBValue;  set { f_CRRefID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_CRRefID { get ; private set; } = new DataLng();



		/// <summary>
		/// Cross Reference sub-identifier.
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? CRRefSubID { get =>  f_CRRefSubID.TypedDBValue;  set { f_CRRefSubID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_CRRefSubID { get ; private set; } = new DataLng();



		/// <summary>
		/// It indicates that the item is cross docking type. It is automatically set by the program according to the item master data, but it can be manually modify by the user.
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? CrossDocking { get =>  f_CrossDocking.TypedDBValue;  set { f_CrossDocking.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_CrossDocking { get ; private set; } = new DataBool();



		/// <summary>
		/// Accounting type phase 1.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? AccountingTypePhase1 { get =>  f_AccountingTypePhase1.TypedDBValue;  set { f_AccountingTypePhase1.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_AccountingTypePhase1 { get ; private set; } = new DataStr();



		/// <summary>
		/// Accounting type phase 2.
		/// 	
		/// DefaultValue: ""
		/// </summary>

		public string? AccountingTypePhase2 { get =>  f_AccountingTypePhase2.TypedDBValue;  set { f_AccountingTypePhase2.TypedDBValue = value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataStr f_AccountingTypePhase2 { get ; private set; } = new DataStr();



		/// <summary>
		/// Field for internal use.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DistributedShipCharges { get =>  f_DistributedShipCharges.TypedDBValue;  set { f_DistributedShipCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DistributedShipCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// Field for internal use.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DistributedAdditionalCharges { get =>  f_DistributedAdditionalCharges.TypedDBValue;  set { f_DistributedAdditionalCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DistributedAdditionalCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// Field for internal use.
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? DistributedPackingCharges { get =>  f_DistributedPackingCharges.TypedDBValue;  set { f_DistributedPackingCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DistributedPackingCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0.00
		/// </summary>

		public double? ToBeAllocatedQty { get =>  f_ToBeAllocatedQty.TypedDBValue;  set { f_ToBeAllocatedQty.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataQty f_ToBeAllocatedQty { get ; private set; } = new DataQty();



		/// <summary>
		/// Deposit
		/// 	
		/// DefaultValue: false
		/// </summary>

		public bool? Deposit { get =>  f_Deposit.TypedDBValue;  set { f_Deposit.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataBool f_Deposit { get ; private set; } = new DataBool();



		/// <summary>
		/// Field used by CGM
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? TBCompanyID { get =>  f_TBCompanyID.TypedDBValue;  set { f_TBCompanyID.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_TBCompanyID { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? DeclarationOfIntentId { get =>  f_DeclarationOfIntentId.TypedDBValue;  set { f_DeclarationOfIntentId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_DeclarationOfIntentId { get ; private set; } = new DataLng();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public double? DistributedDiscount { get =>  f_DistributedDiscount.TypedDBValue;  set { f_DistributedDiscount.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DistributedDiscount { get ; private set; } = new DataMon();



		/// <summary>
		/// 
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public double? DistributedCollectCharges { get =>  f_DistributedCollectCharges.TypedDBValue;  set { f_DistributedCollectCharges.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataMon f_DistributedCollectCharges { get ; private set; } = new DataMon();



		/// <summary>
		/// VariantSubId
		/// 	
		/// DefaultValue: 0
		/// </summary>

		public Int32? VariantSubId { get =>  f_VariantSubId.TypedDBValue;  set { f_VariantSubId.TypedDBValue = value.Value; } }
		/// <summary>
		/// property exposed for value management and field entity
		/// </summary>
		[NotMapped]
		public DataLng f_VariantSubId { get ; private set; } = new DataLng();




	}	

	[Table("MA_SaleOrdDetails")]
    [TbEntityTypeConfiguration(typeof(MA_SaleOrdDetailsConfiguration))]
	public partial class MA_SaleOrdDetails : MA_SaleOrdDetailsObj
	{
		public MA_SaleOrdDetails()
			:base()
		{
		}
	}

	public sealed class MA_SaleOrdDetailsConfiguration : MA_SaleOrdDetailsConfiguration<MA_SaleOrdDetails>
	{
		public MA_SaleOrdDetailsConfiguration(DbType dbType, string subscription) 
			: base(dbType, subscription)
		{
		}

		public override void Configure(EntityTypeBuilder<MA_SaleOrdDetails> entity)
		{
			base.Configure(entity);
		}
	}

	public class MA_SaleOrdDetailsConfiguration<TEntity> : AbstractEntityTypeConfiguration<TEntity> where TEntity : MA_SaleOrdDetailsObj
    {
        public MA_SaleOrdDetailsConfiguration(DbType dbType, string subscription)
            :base(dbType, subscription)
        {
        }

        public override void Configure(EntityTypeBuilder<TEntity> entity)
        { 
		
		#if NET6_0 || NET8_0 || NETCOREAPP3_1 || NETSTANDARD2_1
			entity.HasKey(e => new { e.SaleOrdId,e.Line }).HasName("PK_SaleOrdDetails").IsClustered(false);
		#else
			entity.HasKey(e => new { e.SaleOrdId,e.Line }).HasName("PK_SaleOrdDetails").ForSqlServerIsClustered(false);
		#endif

           
			#region Columns

			if(Database.IsSqlServer())
			{	
					entity.Property(e => e.Line).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Position).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.LineType).HasDefaultValueSql("(3538947)")  ;
					entity.Property(e => e.Description).HasMaxLength(128).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NoPrint).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.NoDN).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.NoInvoice).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Item).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Lot).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Variant).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Drawing).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Customer).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.OrderDate).HasColumnType("datetime").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.InternalOrdNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Department).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.UoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Qty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty1).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty2).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty3).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NetPrice).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NetPriceIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.TaxableAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.TotalAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount1).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount2).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountFormula).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DiscountAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ExpectedDeliveryDate).HasColumnType("datetime").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.ConfirmedDeliveryDate).HasColumnType("datetime").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.DeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PreShippedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.InvoicedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SaleType).HasDefaultValueSql("(3670020)")  ;
					entity.Property(e => e.NoOfPacks).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PacksUoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.GrossWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NetWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GrossVolume).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Delivered).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Invoiced).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PreShipped).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.Cancelled).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.SaleOrdId).HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.KitNo).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.KitQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Job).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CostCenter).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductLine).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CommPerc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AreaManagerCommPerc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SalespersonDiscount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.CommissionCtg).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionPlanId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ProductionPlanNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionPlanLine).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Offset).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.BookedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SalespersonComm).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SubId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.BOMItem).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.StoragePhase1).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.StoragePhase2).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SpecificatorPhase1).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SpecificatorPhase2).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ExternalLineReference).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CustomerLotNo).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionJobId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ProductionJobNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionJobSubId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceDocId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceDocNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ReferenceQuotationId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceQuotationSubId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceQuotation).HasMaxLength(64).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Notes).HasColumnType("ntext").HasDefaultValueSql("('')")  ;
					entity.Property(e => e.BaseSalesperson).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.BaseAreaManager).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AreaManagerComm).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AreaManagerCommCtg).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CommPercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.AreaManagerCommPercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.SalespersonCommAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.AreaManagerCommAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.SalespersonCommCtgAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.AreaManagerCommCtgAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.ConfirmationLevel).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CustomerCode).HasMaxLength(20).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.PriceList).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Picked).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.PickedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PickedAndDeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PreShippedAndDeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Allocated).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.AllocatedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ReferredPosition).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CRRefType).HasDefaultValueSql("(27066368)")  ;
					entity.Property(e => e.CRRefID).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CRRefSubID).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CrossDocking).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.AccountingTypePhase1).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.AccountingTypePhase2).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DistributedShipCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DistributedAdditionalCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DistributedPackingCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ToBeAllocatedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Deposit).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("nchar(1)")  ;
					entity.Property(e => e.TBCompanyID).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.DeclarationOfIntentId).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.DistributedDiscount).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.DistributedCollectCharges).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.VariantSubId).HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("datetime").HasDefaultValueSql("getutcdate()");
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			if(Database.IsNpgsql())
			{	
					entity.Property(e => e.Line).HasColumnType("smallint").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.Position).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.LineType).HasDefaultValueSql("(3538947)")  ;
					entity.Property(e => e.Description).HasMaxLength(128).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.NoPrint).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.NoDN).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.NoInvoice).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Item).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Lot).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Variant).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Drawing).HasMaxLength(21).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Customer).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.OrderDate).HasColumnType("timestamp without time zone").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.InternalOrdNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Department).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.UoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Qty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty1).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty2).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty3).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AdditionalQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.UnitValue).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NetPrice).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NetPriceIsAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.TaxableAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.TaxCode).HasMaxLength(4).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.TotalAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount1).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Discount2).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DiscountFormula).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DiscountAmount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ExpectedDeliveryDate).HasColumnType("timestamp without time zone").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.ConfirmedDeliveryDate).HasColumnType("timestamp without time zone").HasDefaultValueSql("('1799-12-31T00:00:00')")  ;
					entity.Property(e => e.DeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PreShippedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.InvoicedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SaleType).HasDefaultValueSql("(3670020)")  ;
					entity.Property(e => e.NoOfPacks).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.PacksUoM).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.GrossWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.NetWeight).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.GrossVolume).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Delivered).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Invoiced).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PreShipped).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.Cancelled).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.SaleOrdId).HasColumnType("integer").HasDefaultValueSql("('0')").ValueGeneratedNever()  ;
					entity.Property(e => e.KitNo).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.KitQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Job).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CostCenter).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductLine).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CommPerc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AreaManagerCommPerc).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SalespersonDiscount).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.CommissionCtg).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionPlanId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ProductionPlanNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionPlanLine).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.Offset).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.BookedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SalespersonComm).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.SubId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.BOMItem).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.StoragePhase1).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.StoragePhase2).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SpecificatorPhase1).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.SpecificatorPhase2).HasMaxLength(12).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ExternalLineReference).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CustomerLotNo).HasMaxLength(16).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionJobId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ProductionJobNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ProductionJobSubId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceDocId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceDocNo).HasMaxLength(10).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.ReferenceQuotationId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceQuotationSubId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.ReferenceQuotation).HasMaxLength(64).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Notes).HasColumnType("Text").HasDefaultValueSql("('')")  ;
					entity.Property(e => e.BaseSalesperson).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.BaseAreaManager).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AreaManagerComm).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.AreaManagerCommCtg).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CommPercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.AreaManagerCommPercAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.SalespersonCommAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.AreaManagerCommAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.SalespersonCommCtgAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.AreaManagerCommCtgAuto).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.ConfirmationLevel).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.CustomerCode).HasMaxLength(20).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.PriceList).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.Picked).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.PickedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PickedAndDeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.PreShippedAndDeliveredQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Allocated).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.AllocatedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ReferredPosition).HasColumnType("smallint").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CRRefType).HasDefaultValueSql("(27066368)")  ;
					entity.Property(e => e.CRRefID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CRRefSubID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.CrossDocking).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.AccountingTypePhase1).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.AccountingTypePhase2).HasMaxLength(8).HasDefaultValueSql("('')")  ;
					entity.Property(e => e.DistributedShipCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DistributedAdditionalCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.DistributedPackingCharges).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.ToBeAllocatedQty).HasDefaultValueSql("('0.00')")  ;
					entity.Property(e => e.Deposit).HasConversion(new BoolToTwoValuesConverter<char>('0', '1')).HasColumnType("char(1)")  ;
					entity.Property(e => e.TBCompanyID).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.DeclarationOfIntentId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.DistributedDiscount).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.DistributedCollectCharges).HasDefaultValueSql("('0')")  ;
					entity.Property(e => e.VariantSubId).HasColumnType("integer").HasDefaultValueSql("('0')")  ;
			
					entity.Property(e => e.TbCreated).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ; 
					entity.Property(e => e.TbModified).IsRequired().HasColumnType("TIMESTAMP").HasDefaultValueSql("CURRENT_TIMESTAMP") ;
					entity.Property(e => e.TbCreatedId).IsRequired().HasDefaultValueSql("0");
					entity.Property(e => e.TbModifiedId).IsRequired().HasDefaultValueSql("0");
			}

			#endregion

			#region FK
			#endregion

			//AbstractEntityTypeConfiguration Method per AddOnField
			CheckConfiguration(entity);
		}
	}

	/// <summary>
	/// This Aggregate is used to read record based on PrimaryKey of table MA_SaleOrdDetails
	/// </summary>
	public class SaleOrdDetailsAggregate<TContext> : BaseTbAggregate<TContext, MA_SaleOrdDetails>
                                                                            where TContext : TbDbContext
    {
        public SaleOrdDetailsAggregate(TContext context, ITbDiagnostic diagnostic) 
            : base(context, diagnostic)
        {
        }

		private IQueryable<MA_SaleOrdDetails> Query(Int32 saleOrdId,Int16 line)
			=> EntityDbSet.Where(x => x.SaleOrdId == saleOrdId && x.Line == line);

		#region SyncMethods 
		/// <summary>
		/// Return SaleOrdDetails based on primary key parameters or default of TResult if not found 
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order lines with the head of the same document.</param>
		
		/// <param name="line">It indicates the position in the grid of each document line. It is, together with SaleOrdId, the table key.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public TResult GetSaleOrdDetails<TResult>(Int32 saleOrdId,Int16 line,
		                                       Expression<Func<MA_SaleOrdDetails, TResult>> selector, TResult @default = default)		
			=> Result(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdDetails based on primary key parameters
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order lines with the head of the same document.</param>
		
		/// <param name="line">It indicates the position in the grid of each document line. It is, together with SaleOrdId, the table key.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public ITbResult<TResult> GetSaleOrdDetailsTbResult<TResult>(Int32 saleOrdId,Int16 line,
		                                                          Expression<Func<MA_SaleOrdDetails, TResult>> selector, TResult @default = default)
			=> TbResult(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdDetails based on primary key parameters default of MA_SaleOrdDetails if not found
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdDetails with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links the order lines with the head of the same document.</param>
		
		/// <param name="line">It indicates the position in the grid of each document line. It is, together with SaleOrdId, the table key.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdDetails or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdDetails with selector parameter")]
        public MA_SaleOrdDetails GetSaleOrdDetails(Int32 saleOrdId,Int16 line,
												   MA_SaleOrdDetails @default = default)
			=> Result(Query(saleOrdId,line), @default);
		#endregion


		#region AsyncMethods
		/// <summary>
		/// Return SaleOrdDetails based on primary key parameters or default of TResult if not found with Async method
		/// </summary>
		/// <remarks>be careful on default of TResult of non reference types.</remarks>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order lines with the head of the same document.</param>
		
		/// <param name="line">It indicates the position in the grid of each document line. It is, together with SaleOrdId, the table key.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>TResult based on projection function 'selector' or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<TResult> GetSaleOrdDetailsAsync<TResult>(Int32 saleOrdId,Int16 line,
		                                       Expression<Func<MA_SaleOrdDetails, TResult>> selector, TResult @default = default)		
			=> ResultAsync(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return ITbResult of SaleOrdDetails based on primary key parameters with Async method
		/// </summary>
		/// <typeparam name="TResult">Generic TResult</typeparam>
		
		/// <param name="saleOrdId">It links the order lines with the head of the same document.</param>
		
		/// <param name="line">It indicates the position in the grid of each document line. It is, together with SaleOrdId, the table key.</param>
		
		/// <param name="selector">Project the founded element into a new form.</param>
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>ITbResult based on projection function 'selector'</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        public Task<ITbResult<TResult>> GetSaleOrdDetailsTbResultAsync<TResult>(Int32 saleOrdId,Int16 line,
		                                                          Expression<Func<MA_SaleOrdDetails, TResult>> selector, TResult @default = default)
			=> TbResultAsync(Query(saleOrdId,line).Select(selector), @default);

		/// <summary>
		/// Return SaleOrdDetails based on primary key parameters default of MA_SaleOrdDetails if not found with Async method
		/// </summary>
        /// <remarks>Prefered to use GetSaleOrdDetails with selector parameter</remarks>
		
		/// <param name="saleOrdId">It links the order lines with the head of the same document.</param>
		
		/// <param name="line">It indicates the position in the grid of each document line. It is, together with SaleOrdId, the table key.</param>
		
		/// <param name="default">default value returned if no value is found</param>
		/// <returns>An istance of MA_SaleOrdDetails or default if not found</returns>
        /// <exception cref="InvalidOperationException">Throw when result has more than one element.</exception>
        [Obsolete("Prefered to use GetSaleOrdDetails with selector parameter")]
        public Task<MA_SaleOrdDetails> GetSaleOrdDetailsAsync(Int32 saleOrdId,Int16 line,
												   MA_SaleOrdDetails @default = default)
			=> ResultAsync(Query(saleOrdId,line), @default);

		#endregion 
		
    }

}