// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using Courses.Courses.Courses;
using Microarea.Interfaces;
using Newtonsoft.Json.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.Extensions.Primitives;
using Microarea.Tbf.Model.MyMagoStudioBase;
using Microarea.Generic.DiagnosticManager;
using System.Collections.Generic;

namespace Courses.Courses.Controllers
{
    [ApiController]
    [Route("Courses-Courses-service/[controller]")]
    [ApiExplorerSettings(GroupName = "CoursesCoursesCourses")]
    public class CoursesCoursesCoursesController : MyMagoStudioController<CoursesCoursesCourses, CoursesCoursesCoursesContext>
    {
        public CoursesCoursesCoursesController(IServiceProvider serviceProvider) : base(serviceProvider) { }

        /// <summary>
        /// Complete your business logic for manage your data's state (visible/readonly)
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("CourseCE")]
        public async Task<IActionResult> CourseCE([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<CourseCERequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.CourseCE(req as CourseCERequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as CourseCEResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for manage data and/or data's status (visible/readobly)
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("CourseLevelVC")]
        public async Task<IActionResult> CourseLevelVC([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<CourseLevelVCRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.CourseLevelVC(req as CourseLevelVCRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as CourseLevelVCResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for validate your data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("CourseDFTC")]
        public async Task<IActionResult> CourseDFTC([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<CourseDFTCRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.CourseDFTC(req as CourseDFTCRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as CourseDFTCResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for set your data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("TeacherValidated")]
        public async Task<IActionResult> TeacherValidated([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<TeacherValidatedRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.TeacherValidated(req as TeacherValidatedRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as TeacherValidatedResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for manage data and/or data's status (visible/readobly)
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("CustSuppTypeVC")]
        public async Task<IActionResult> CustSuppTypeVC([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<CustSuppTypeVCRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.CustSuppTypeVC(req as CustSuppTypeVCRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as CustSuppTypeVCResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for complete your data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("CourseDL")]
        public async Task<IActionResult> CourseDL([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<CourseDLRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.CourseDL(req as CourseDLRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as CourseDLResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
    } 
}