// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using CoursesCourses.DuplicateCourses;
using Microarea.Interfaces;
using Newtonsoft.Json.Linq;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using Microsoft.Extensions.Primitives;
using Microarea.Tbf.Model.MyMagoStudioBase;
using Microarea.Generic.DiagnosticManager;
using System.Collections.Generic;

namespace Courses.Courses.Controllers
{
    [ApiController]
    [Route("Courses-Courses-service/[controller]")]
    [ApiExplorerSettings(GroupName = "CoursesCoursesDuplicateCourses")]
    public class CoursesCoursesDuplicateCoursesController : MyMagoStudioController<CoursesCoursesDuplicateCourses, CoursesCoursesDuplicateCoursesContext>
    {
        public CoursesCoursesDuplicateCoursesController(IServiceProvider serviceProvider) : base(serviceProvider) { }

        /// <summary>
        /// Complete your business logic for validate your data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("DuplicateCoursesDFTC")]
        public async Task<IActionResult> DuplicateCoursesDFTC([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<DuplicateCoursesDFTCRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.DuplicateCoursesDFTC(req as DuplicateCoursesDFTCRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as DuplicateCoursesDFTCResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for extract data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("DuplicateCoursesED")]
        public async Task<IActionResult> DuplicateCoursesED([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<DuplicateCoursesEDRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.DuplicateCoursesED(req as DuplicateCoursesEDRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as DuplicateCoursesEDResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for elaborate your data
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("DuplicateCoursesBE")]
        public async Task<IActionResult> DuplicateCoursesBE([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<DuplicateCoursesBERequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.DuplicateCoursesBE(req as DuplicateCoursesBERequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as DuplicateCoursesBEResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
        /// <summary>
        /// Complete your business logic for button click
        /// </summary>
        /// <param name="request"></param>
        /// <returns></returns>
        [HttpPost("uploadFile")]
        public async Task<IActionResult> uploadFile([FromBody] JObject request)
        {
            try
            {
                (bool ok, string message) = ProcessParameters<uploadFileRequest>(request);
                if (!ok)
                    return MyMagoStudioResponse( ok, message,DiagnosticType.Error);

                response = await document.uploadFile(req as uploadFileRequest, ContextInfo, callerDocId);
                return response is null ?
                    MyMagoStudioResponse(false, "Response object is null", DiagnosticType.Error) :
                    new OkObjectResult((response as uploadFileResponse).ToJson());
            }
            catch (Exception e)
            {
                return MyMagoStudioResponse(false, e.Message, DiagnosticType.FatalError); 
            }           
        }
    } 
}