// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public sealed class CourseLevelVCRequest: BaseRequest
    {
        [JsonProperty("CourseLevelIN")]
        public int CourseLevelIN { get; set; }
    }

    public sealed class CourseLevelVCResponse : BaseResponse
    {        
        [JsonProperty("CourseDaysOUT")]
        public Int16 CourseDaysOUT { get; set; } 
    }
}