// DO NOT MODIFY THIS FILE; automatically generated by MMS
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace Courses.Courses.Courses
{
    public partial class CoursesCoursesCourses : MyMagoStudioDocument
    {
        private CoursesCoursesCoursesContext dbContext { get; set; }

        public CoursesCoursesCourses() { }

        public CoursesCoursesCourses(CoursesCoursesCoursesContext dbContext, MyMagoStudioDocumentStatus myMagoStudioDocumentStatus)
            : base(myMagoStudioDocumentStatus)
        { 
            this.dbContext = dbContext;
        }
    }
}