// DO NOT MODIFY THIS FILE; automatically generated by MMS
using Microarea.Tbf.Model.Database;
using Microarea.Tbf.Model.Interfaces.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;

namespace Courses.Courses.Courses
{
    public partial class CoursesCoursesCoursesContext : TbDbContext
    {
        public CoursesCoursesCoursesContext(DbType type, string connectionString, string subscription, DbDataContextProduct product, ICheckAddOn checkAddOn = null, ILoggerFactory logFactory = null)
       
            : base(type, connectionString, subscription, product, checkAddOn, logFactory)
        {
        }
    }
}