// DO NOT MODIFY THIS FILE; automatically generated by MMS
using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Microarea.Generic.DataObj;
using Courses.Courses.Model;
using Microarea.Tbf.Model.MyMagoStudioBase;

namespace CoursesCourses.DuplicateCourses
{
    public sealed class DuplicateCoursesEDRequest: BaseRequest
    {
        [JsonProperty("FiltersIN")]
        public MMS_Filters FiltersIN { get; set; }
        
    }

    public sealed class DuplicateCoursesEDResponse : BaseResponse
    {        
        [JsonProperty("ResultsOUT")]
        
        public MyMagoStudioOneToManyResponse<MMS_Results> ResultsOUT { get; set; } = new MyMagoStudioOneToManyResponse<MMS_Results>();
    }
}